import '../models/quiz.dart';

class QuizService {
  // Mock quiz data - in production, fetch from API
  
  List<Quiz> getQuizzesByCategory(QuizCategory category) {
    return _mockQuizzes.where((quiz) => quiz.category == category).toList();
  }

  Quiz? getQuizById(String id) {
    try {
      return _mockQuizzes.firstWhere((quiz) => quiz.id == id);
    } catch (e) {
      return null;
    }
  }

  List<Quiz> getAllQuizzes() {
    return _mockQuizzes;
  }

  Future<List<QuizResult>> getUserResults(String userId) async {
    // Simulate API call
    await Future.delayed(const Duration(milliseconds: 500));
    // Return mock results or fetch from API
    return [];
  }

  Future<void> submitQuizResult(QuizResult result) async {
    // Simulate API call
    await Future.delayed(const Duration(milliseconds: 500));
    // Submit to API in production
  }

  // Mock quiz data
  static final List<Quiz> _mockQuizzes = [
    Quiz(
      id: 'poker_1',
      title: 'Poker Fundamentals',
      category: QuizCategory.poker,
      timeLimit: 600,
      passingScore: 70,
      questions: [
        Question(
          id: 'p1',
          question: 'What is the best possible starting hand in Texas Hold\'em?',
          options: ['Ace-King suited', 'Pocket Aces', 'Pocket Kings', 'Queen-Jack suited'],
          correctAnswerIndex: 1,
          category: QuizCategory.poker,
          explanation: 'Pocket Aces (AA) is statistically the strongest starting hand in Texas Hold\'em poker.',
          points: 10,
        ),
        Question(
          id: 'p2',
          question: 'How many community cards are dealt in Texas Hold\'em?',
          options: ['3', '4', '5', '7'],
          correctAnswerIndex: 2,
          category: QuizCategory.poker,
          explanation: 'Five community cards are dealt: three on the flop, one on the turn, and one on the river.',
          points: 10,
        ),
        Question(
          id: 'p3',
          question: 'What beats a flush in poker?',
          options: ['Straight', 'Three of a kind', 'Full house', 'Two pair'],
          correctAnswerIndex: 2,
          category: QuizCategory.poker,
          explanation: 'A full house (three of a kind + a pair) beats a flush. Straight flush and royal flush also beat it.',
          points: 10,
        ),
        Question(
          id: 'p4',
          question: 'What is the term for the first three community cards dealt?',
          options: ['The River', 'The Turn', 'The Flop', 'The Deal'],
          correctAnswerIndex: 2,
          category: QuizCategory.poker,
          explanation: 'The Flop is the first three community cards dealt face-up in Texas Hold\'em.',
          points: 10,
        ),
        Question(
          id: 'p5',
          question: 'In poker, what does "all-in" mean?',
          options: ['Fold your hand', 'Bet all your chips', 'Check', 'Call the bet'],
          correctAnswerIndex: 1,
          category: QuizCategory.poker,
          explanation: 'Going "all-in" means betting all of your remaining chips on the current hand.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'blackjack_1',
      title: 'Blackjack Basics',
      category: QuizCategory.blackjack,
      timeLimit: 600,
      passingScore: 70,
      questions: [
        Question(
          id: 'b1',
          question: 'What is the goal in Blackjack?',
          options: ['Get exactly 21', 'Beat the dealer without going over 21', 'Get the highest score', 'Match the dealer'],
          correctAnswerIndex: 1,
          category: QuizCategory.blackjack,
          explanation: 'The goal is to beat the dealer by having a hand value closer to 21 without exceeding it.',
          points: 10,
        ),
        Question(
          id: 'b2',
          question: 'What is the value of an Ace in Blackjack?',
          options: ['Always 1', 'Always 11', '1 or 11', '10'],
          correctAnswerIndex: 2,
          category: QuizCategory.blackjack,
          explanation: 'An Ace can be worth either 1 or 11, depending on which value benefits the hand more.',
          points: 10,
        ),
        Question(
          id: 'b3',
          question: 'What is a "blackjack" hand?',
          options: ['Any hand totaling 21', 'Ace and a 10-value card', 'Three sevens', 'Five cards under 21'],
          correctAnswerIndex: 1,
          category: QuizCategory.blackjack,
          explanation: 'A "blackjack" is specifically an Ace combined with any 10-value card (10, J, Q, K) as the first two cards.',
          points: 10,
        ),
        Question(
          id: 'b4',
          question: 'What does "doubling down" mean?',
          options: ['Splitting pairs', 'Doubling your bet for one more card', 'Surrendering', 'Taking insurance'],
          correctAnswerIndex: 1,
          category: QuizCategory.blackjack,
          explanation: 'Doubling down means doubling your initial bet in exchange for receiving exactly one more card.',
          points: 10,
        ),
        Question(
          id: 'b5',
          question: 'At what hand value does the dealer typically stand?',
          options: ['16', '17', '18', '19'],
          correctAnswerIndex: 1,
          category: QuizCategory.blackjack,
          explanation: 'Most casino rules require the dealer to stand on 17 or higher and hit on 16 or lower.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'roulette_1',
      title: 'Roulette Rules',
      category: QuizCategory.roulette,
      timeLimit: 600,
      passingScore: 70,
      questions: [
        Question(
          id: 'r1',
          question: 'How many numbers are on a European roulette wheel?',
          options: ['36', '37', '38', '39'],
          correctAnswerIndex: 1,
          category: QuizCategory.roulette,
          explanation: 'European roulette has 37 numbers: 1-36 plus a single zero (0).',
          points: 10,
        ),
        Question(
          id: 'r2',
          question: 'What is the house edge in American roulette?',
          options: ['2.7%', '5.26%', '1.35%', '3.5%'],
          correctAnswerIndex: 1,
          category: QuizCategory.roulette,
          explanation: 'American roulette has a house edge of 5.26% due to the double zero (00).',
          points: 10,
        ),
        Question(
          id: 'r3',
          question: 'What color is the zero pocket in roulette?',
          options: ['Red', 'Black', 'Green', 'Yellow'],
          correctAnswerIndex: 2,
          category: QuizCategory.roulette,
          explanation: 'The zero (and double zero in American roulette) are always green.',
          points: 10,
        ),
        Question(
          id: 'r4',
          question: 'What is a "straight up" bet in roulette?',
          options: ['Betting on red or black', 'Betting on a single number', 'Betting on a column', 'Betting on even/odd'],
          correctAnswerIndex: 1,
          category: QuizCategory.roulette,
          explanation: 'A straight up bet is a bet on a single number, offering the highest payout of 35:1.',
          points: 10,
        ),
        Question(
          id: 'r5',
          question: 'What is the payout for a red/black bet in roulette?',
          options: ['1:1', '2:1', '3:1', '35:1'],
          correctAnswerIndex: 0,
          category: QuizCategory.roulette,
          explanation: 'Red/black, even/odd, and high/low are all even money bets with a 1:1 payout.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'slots_1',
      title: 'Slot Machine Secrets',
      category: QuizCategory.slots,
      timeLimit: 600,
      passingScore: 70,
      questions: [
        Question(
          id: 's1',
          question: 'What does RTP stand for in slot machines?',
          options: ['Return To Player', 'Random Type Pattern', 'Real Time Profit', 'Rotation Time Period'],
          correctAnswerIndex: 0,
          category: QuizCategory.slots,
          explanation: 'RTP stands for Return To Player, indicating the percentage of wagered money paid back over time.',
          points: 10,
        ),
        Question(
          id: 's2',
          question: 'What is a progressive jackpot?',
          options: ['A fixed jackpot', 'A jackpot that increases with each bet', 'A bonus round', 'Free spins'],
          correctAnswerIndex: 1,
          category: QuizCategory.slots,
          explanation: 'A progressive jackpot grows with each bet placed on the game until someone wins it.',
          points: 10,
        ),
        Question(
          id: 's3',
          question: 'What determines the outcome of a slot spin?',
          options: ['Time of day', 'Random Number Generator', 'Previous spins', 'Bet amount'],
          correctAnswerIndex: 1,
          category: QuizCategory.slots,
          explanation: 'A Random Number Generator (RNG) ensures each spin is completely random and independent.',
          points: 10,
        ),
        Question(
          id: 's4',
          question: 'What are paylines in slot machines?',
          options: ['Bonus features', 'Lines on which winning combinations are paid', 'Free spin triggers', 'Jackpot amounts'],
          correctAnswerIndex: 1,
          category: QuizCategory.slots,
          explanation: 'Paylines are the lines on which matching symbols must appear to create a winning combination.',
          points: 10,
        ),
        Question(
          id: 's5',
          question: 'What is volatility in slots?',
          options: ['Game speed', 'Risk and reward level', 'Number of reels', 'Bonus frequency'],
          correctAnswerIndex: 1,
          category: QuizCategory.slots,
          explanation: 'Volatility indicates risk level: high volatility means bigger but less frequent wins.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'general_1',
      title: 'Casino Knowledge Pro',
      category: QuizCategory.general,
      timeLimit: 900,
      passingScore: 75,
      questions: [
        Question(
          id: 'g1',
          question: 'What is the house edge?',
          options: ['Player advantage', 'Casino advantage', 'Break-even point', 'Maximum bet'],
          correctAnswerIndex: 1,
          category: QuizCategory.general,
          explanation: 'The house edge is the mathematical advantage the casino has over players in any given game.',
          points: 10,
        ),
        Question(
          id: 'g2',
          question: 'Which game typically has the lowest house edge?',
          options: ['Slots', 'Roulette', 'Blackjack', 'Keno'],
          correctAnswerIndex: 2,
          category: QuizCategory.general,
          explanation: 'Blackjack, when played with optimal strategy, typically has the lowest house edge (around 0.5%).',
          points: 10,
        ),
        Question(
          id: 'g3',
          question: 'What are "comps" in a casino?',
          options: ['Competitions', 'Complimentary rewards', 'Computer games', 'Compensation for losses'],
          correctAnswerIndex: 1,
          category: QuizCategory.general,
          explanation: 'Comps are complimentary items or services casinos offer to players based on their play.',
          points: 10,
        ),
        Question(
          id: 'g4',
          question: 'What is card counting?',
          options: ['Illegal cheating', 'Mental strategy to track cards', 'Using devices', 'Marking cards'],
          correctAnswerIndex: 1,
          category: QuizCategory.general,
          explanation: 'Card counting is a legal mental strategy used in blackjack to track the ratio of high to low cards.',
          points: 10,
        ),
        Question(
          id: 'g5',
          question: 'What does "bankroll management" mean?',
          options: ['Borrowing money', 'Managing your gambling budget', 'Casino accounting', 'Withdrawal limits'],
          correctAnswerIndex: 1,
          category: QuizCategory.general,
          explanation: 'Bankroll management is the practice of responsibly managing your gambling budget to avoid losses.',
          points: 10,
        ),
        Question(
          id: 'g6',
          question: 'What is a "whale" in casino terminology?',
          options: ['Beginner player', 'High roller', 'Casino employee', 'Lucky player'],
          correctAnswerIndex: 1,
          category: QuizCategory.general,
          explanation: 'A "whale" is casino slang for a high roller who bets very large amounts of money.',
          points: 10,
        ),
        Question(
          id: 'g7',
          question: 'What is the purpose of casino chips?',
          options: ['Decoration', 'Standardize bets and reduce theft', 'Slow down play', 'Track players'],
          correctAnswerIndex: 1,
          category: QuizCategory.general,
          explanation: 'Chips standardize betting amounts, speed up gameplay, and reduce the risk of theft.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'poker_2',
      title: 'Advanced Poker Strategy',
      category: QuizCategory.poker,
      timeLimit: 600,
      passingScore: 75,
      questions: [
        Question(
          id: 'p6',
          question: 'What does "GTO" stand for in poker?',
          options: ['Game Theory Optimal', 'Go To Odds', 'Great Table Options', 'Guaranteed Total Outcome'],
          correctAnswerIndex: 0,
          category: QuizCategory.poker,
          explanation: 'GTO stands for Game Theory Optimal, a balanced strategy that cannot be exploited.',
          points: 10,
        ),
        Question(
          id: 'p7',
          question: 'What is a continuation bet (c-bet)?',
          options: ['Betting after winning', 'Betting again on next street', 'Matching the previous bet', 'Doubling your stake'],
          correctAnswerIndex: 1,
          category: QuizCategory.poker,
          explanation: 'A c-bet is when the pre-flop aggressor bets again on the flop to continue showing strength.',
          points: 10,
        ),
        Question(
          id: 'p8',
          question: 'What position is "under the gun"?',
          options: ['Dealer position', 'First to act pre-flop', 'Last to act', 'Big blind'],
          correctAnswerIndex: 1,
          category: QuizCategory.poker,
          explanation: 'Under the gun (UTG) is the position directly left of the big blind, first to act pre-flop.',
          points: 10,
        ),
        Question(
          id: 'p9',
          question: 'What are "pot odds"?',
          options: ['Chance of winning', 'Ratio of pot size to bet size', 'Tournament payouts', 'Rake percentage'],
          correctAnswerIndex: 1,
          category: QuizCategory.poker,
          explanation: 'Pot odds are the ratio between the current pot size and the cost to call a bet.',
          points: 10,
        ),
        Question(
          id: 'p10',
          question: 'What is a "bad beat"?',
          options: ['Playing poorly', 'Losing with a strong hand', 'Missing the flop', 'Getting bluffed'],
          correctAnswerIndex: 1,
          category: QuizCategory.poker,
          explanation: 'A bad beat is when you lose a hand despite having a statistically strong advantage.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'blackjack_2',
      title: 'Blackjack Advanced',
      category: QuizCategory.blackjack,
      timeLimit: 600,
      passingScore: 75,
      questions: [
        Question(
          id: 'b6',
          question: 'What is "basic strategy" in blackjack?',
          options: ['Always hit on 16', 'Mathematically optimal play chart', 'Card counting system', 'Betting progression'],
          correctAnswerIndex: 1,
          category: QuizCategory.blackjack,
          explanation: 'Basic strategy is a mathematically proven chart showing the optimal decision for every hand.',
          points: 10,
        ),
        Question(
          id: 'b7',
          question: 'When should you split 8s?',
          options: ['Never', 'Only against dealer 2-6', 'Always', 'Only when losing'],
          correctAnswerIndex: 2,
          category: QuizCategory.blackjack,
          explanation: 'You should always split 8s in blackjack as it improves your expected value.',
          points: 10,
        ),
        Question(
          id: 'b8',
          question: 'What is "insurance" in blackjack?',
          options: ['Side bet on dealer blackjack', 'Protection against losses', 'Chip insurance', 'Dealer tip'],
          correctAnswerIndex: 0,
          category: QuizCategory.blackjack,
          explanation: 'Insurance is a side bet offered when dealer shows an Ace, betting they have blackjack.',
          points: 10,
        ),
        Question(
          id: 'b9',
          question: 'What is a "soft 17"?',
          options: ['17 with face cards', 'Ace counted as 11 making 17', '17 after splitting', '17 from doubling'],
          correctAnswerIndex: 1,
          category: QuizCategory.blackjack,
          explanation: 'A soft 17 is a hand containing an Ace counted as 11 (like A-6), totaling 17.',
          points: 10,
        ),
        Question(
          id: 'b10',
          question: 'What is "penetration" in blackjack?',
          options: ['Card counting depth', 'How far into deck before shuffle', 'Bet sizing', 'Table rules'],
          correctAnswerIndex: 1,
          category: QuizCategory.blackjack,
          explanation: 'Penetration refers to how many cards are dealt before the dealer reshuffles the deck.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'roulette_2',
      title: 'Roulette Master',
      category: QuizCategory.roulette,
      timeLimit: 600,
      passingScore: 70,
      questions: [
        Question(
          id: 'r6',
          question: 'What is a "street bet" in roulette?',
          options: ['Betting on a row of 3 numbers', 'Outside bet', 'Betting on red/black', 'Corner bet'],
          correctAnswerIndex: 0,
          category: QuizCategory.roulette,
          explanation: 'A street bet covers three consecutive numbers in a horizontal row, paying 11:1.',
          points: 10,
        ),
        Question(
          id: 'r7',
          question: 'What is the "en prison" rule?',
          options: ['Betting limit', 'Zero landing keeps bet', 'Maximum bet rule', 'Spin again rule'],
          correctAnswerIndex: 1,
          category: QuizCategory.roulette,
          explanation: 'En prison rule allows even-money bets to remain when 0 hits, waiting for next spin.',
          points: 10,
        ),
        Question(
          id: 'r8',
          question: 'What is a "corner bet"?',
          options: ['Four numbers meeting at corner', 'Edge of table', 'Zero bet', 'Outside bet'],
          correctAnswerIndex: 0,
          category: QuizCategory.roulette,
          explanation: 'A corner bet covers four numbers that meet at one corner, paying 8:1.',
          points: 10,
        ),
        Question(
          id: 'r9',
          question: 'What is the difference between inside and outside bets?',
          options: ['Table position', 'Payout odds', 'Bet amount', 'Winning chance'],
          correctAnswerIndex: 1,
          category: QuizCategory.roulette,
          explanation: 'Inside bets are on numbered grid (higher odds), outside bets are groups (lower odds).',
          points: 10,
        ),
        Question(
          id: 'r10',
          question: 'What is a "dozen bet"?',
          options: ['12 numbers in sequence', '1-12, 13-24, or 25-36', 'Any 12 numbers', 'First dozen spins'],
          correctAnswerIndex: 1,
          category: QuizCategory.roulette,
          explanation: 'A dozen bet covers one of three groups: 1-12, 13-24, or 25-36, paying 2:1.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'slots_2',
      title: 'Slots Expert',
      category: QuizCategory.slots,
      timeLimit: 600,
      passingScore: 70,
      questions: [
        Question(
          id: 's6',
          question: 'What is a "wild symbol" in slots?',
          options: ['Bonus trigger', 'Substitutes for other symbols', 'Scatter symbol', 'Jackpot symbol'],
          correctAnswerIndex: 1,
          category: QuizCategory.slots,
          explanation: 'Wild symbols substitute for other symbols to help create winning combinations.',
          points: 10,
        ),
        Question(
          id: 's7',
          question: 'What are "scatter symbols"?',
          options: ['Pay anywhere on reels', 'Only on paylines', 'Bonus only', 'Wild cards'],
          correctAnswerIndex: 0,
          category: QuizCategory.slots,
          explanation: 'Scatter symbols pay regardless of position and often trigger bonus features.',
          points: 10,
        ),
        Question(
          id: 's8',
          question: 'What is "max bet" in slots?',
          options: ['Table limit', 'Maximum coins per spin', 'Jackpot requirement', 'VIP feature'],
          correctAnswerIndex: 1,
          category: QuizCategory.slots,
          explanation: 'Max bet is the highest amount you can wager per spin, often required for jackpots.',
          points: 10,
        ),
        Question(
          id: 's9',
          question: 'What are "free spins"?',
          options: ['Bonus spins without wagering', 'First game spins', 'Demo mode', 'Win multipliers'],
          correctAnswerIndex: 0,
          category: QuizCategory.slots,
          explanation: 'Free spins are bonus rounds where you spin without using your own money.',
          points: 10,
        ),
        Question(
          id: 's10',
          question: 'What is "hit frequency" in slots?',
          options: ['Spin speed', 'How often wins occur', 'Jackpot rate', 'Bonus triggers'],
          correctAnswerIndex: 1,
          category: QuizCategory.slots,
          explanation: 'Hit frequency is the percentage of spins that result in any win.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'baccarat_1',
      title: 'Baccarat Basics',
      category: QuizCategory.baccarat,
      timeLimit: 600,
      passingScore: 70,
      questions: [
        Question(
          id: 'ba1',
          question: 'What is the goal in Baccarat?',
          options: ['Get 21', 'Closest to 9', 'Beat dealer', 'Get blackjack'],
          correctAnswerIndex: 1,
          category: QuizCategory.baccarat,
          explanation: 'The goal in Baccarat is to bet on the hand that will be closest to 9.',
          points: 10,
        ),
        Question(
          id: 'ba2',
          question: 'How many betting options are there in Baccarat?',
          options: ['2', '3', '4', '5'],
          correctAnswerIndex: 1,
          category: QuizCategory.baccarat,
          explanation: 'You can bet on Player, Banker, or Tie in standard Baccarat.',
          points: 10,
        ),
        Question(
          id: 'ba3',
          question: 'What is the house edge on Banker bet?',
          options: ['5.26%', '2.7%', '1.06%', '0.5%'],
          correctAnswerIndex: 2,
          category: QuizCategory.baccarat,
          explanation: 'The Banker bet has the lowest house edge at approximately 1.06%.',
          points: 10,
        ),
        Question(
          id: 'ba4',
          question: 'What is the commission on winning Banker bets?',
          options: ['2%', '3%', '5%', '10%'],
          correctAnswerIndex: 2,
          category: QuizCategory.baccarat,
          explanation: 'Casinos typically charge a 5% commission on winning Banker bets.',
          points: 10,
        ),
        Question(
          id: 'ba5',
          question: 'What value do face cards have in Baccarat?',
          options: ['10', '0', '5', '1'],
          correctAnswerIndex: 1,
          category: QuizCategory.baccarat,
          explanation: 'In Baccarat, face cards (Jack, Queen, King) and 10s are worth 0 points.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'baccarat_2',
      title: 'Baccarat Drawing Rules',
      category: QuizCategory.baccarat,
      timeLimit: 600,
      passingScore: 75,
      questions: [
        Question(
          id: 'ba6',
          question: 'When does Player hand draw a third card?',
          options: ['Always', 'When total is 0-5', 'When total is 0-6', 'Never'],
          correctAnswerIndex: 1,
          category: QuizCategory.baccarat,
          explanation: 'Player draws a third card when the initial two-card total is 0-5.',
          points: 10,
        ),
        Question(
          id: 'ba7',
          question: 'When does Player stand?',
          options: ['6-7', '8-9', 'Both A and B', '5-9'],
          correctAnswerIndex: 2,
          category: QuizCategory.baccarat,
          explanation: 'Player stands on 6-7 and natural 8-9.',
          points: 10,
        ),
        Question(
          id: 'ba8',
          question: 'What is a "natural" in Baccarat?',
          options: ['Any 9', '8 or 9 in first two cards', 'Three card total', 'Tie result'],
          correctAnswerIndex: 1,
          category: QuizCategory.baccarat,
          explanation: 'A natural is an 8 or 9 with the first two cards, ending the hand immediately.',
          points: 10,
        ),
        Question(
          id: 'ba9',
          question: 'How many cards maximum in Baccarat hand?',
          options: ['2', '3', '4', '5'],
          correctAnswerIndex: 1,
          category: QuizCategory.baccarat,
          explanation: 'Each hand in Baccarat consists of a maximum of three cards.',
          points: 10,
        ),
        Question(
          id: 'ba10',
          question: 'Does Banker drawing depend on Player third card?',
          options: ['No, independent', 'Yes, complex rules', 'Only sometimes', 'Only on naturals'],
          correctAnswerIndex: 1,
          category: QuizCategory.baccarat,
          explanation: 'Banker\'s third card draw follows complex rules based on Player\'s third card value.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'baccarat_3',
      title: 'Baccarat Variations',
      category: QuizCategory.baccarat,
      timeLimit: 600,
      passingScore: 70,
      questions: [
        Question(
          id: 'ba11',
          question: 'What is Punto Banco?',
          options: ['Spanish baccarat', 'American/standard baccarat', 'Asian version', 'Mini baccarat'],
          correctAnswerIndex: 1,
          category: QuizCategory.baccarat,
          explanation: 'Punto Banco is the standard North American version of baccarat.',
          points: 10,
        ),
        Question(
          id: 'ba12',
          question: 'What is Chemin de Fer?',
          options: ['Railroad baccarat', 'French version where players bank', 'Fast baccarat', 'Side bet'],
          correctAnswerIndex: 1,
          category: QuizCategory.baccarat,
          explanation: 'Chemin de Fer is French baccarat where players take turns being banker.',
          points: 10,
        ),
        Question(
          id: 'ba13',
          question: 'What is Baccarat Banque?',
          options: ['Banking version', 'Three-hand version', 'High limit', 'Tournament style'],
          correctAnswerIndex: 1,
          category: QuizCategory.baccarat,
          explanation: 'Baccarat Banque uses three decks and features three hands instead of two.',
          points: 10,
        ),
        Question(
          id: 'ba14',
          question: 'What is Mini Baccarat?',
          options: ['Children\'s version', 'Lower stakes, faster play', 'Fewer cards', 'Online only'],
          correctAnswerIndex: 1,
          category: QuizCategory.baccarat,
          explanation: 'Mini Baccarat is a simplified, faster version with lower table minimums.',
          points: 10,
        ),
        Question(
          id: 'ba15',
          question: 'What is EZ Baccarat?',
          options: ['Easy rules', 'No commission on Banker', 'Online version', 'Beginner tables'],
          correctAnswerIndex: 1,
          category: QuizCategory.baccarat,
          explanation: 'EZ Baccarat removes the 5% commission but Banker 3-card 7 pushes.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'baccarat_4',
      title: 'Baccarat Strategy',
      category: QuizCategory.baccarat,
      timeLimit: 600,
      passingScore: 70,
      questions: [
        Question(
          id: 'ba16',
          question: 'What is the best bet in Baccarat?',
          options: ['Player', 'Banker', 'Tie', 'All equal'],
          correctAnswerIndex: 1,
          category: QuizCategory.baccarat,
          explanation: 'Banker bet has the lowest house edge at 1.06%, making it the best bet.',
          points: 10,
        ),
        Question(
          id: 'ba17',
          question: 'Should you ever bet on Tie?',
          options: ['Yes, highest payout', 'No, worst house edge', 'Sometimes', 'Only in mini-baccarat'],
          correctAnswerIndex: 1,
          category: QuizCategory.baccarat,
          explanation: 'Tie bets have a house edge over 14%, making them the worst bet in baccarat.',
          points: 10,
        ),
        Question(
          id: 'ba18',
          question: 'Does card counting work in Baccarat?',
          options: ['Yes, very effective', 'Barely, not worth effort', 'Only in Chemin de Fer', 'Yes, like blackjack'],
          correctAnswerIndex: 1,
          category: QuizCategory.baccarat,
          explanation: 'Card counting in baccarat provides minimal advantage and is not practical.',
          points: 10,
        ),
        Question(
          id: 'ba19',
          question: 'Should you follow betting patterns?',
          options: ['Yes, track shoes', 'No, each hand independent', 'Only in streaks', 'Yes, use scorecards'],
          correctAnswerIndex: 1,
          category: QuizCategory.baccarat,
          explanation: 'Each hand is independent; past results don\'t predict future outcomes.',
          points: 10,
        ),
        Question(
          id: 'ba20',
          question: 'What is bankroll management key in Baccarat?',
          options: ['Bet more when winning', 'Set win/loss limits', 'Chase losses', 'Max bet always'],
          correctAnswerIndex: 1,
          category: QuizCategory.baccarat,
          explanation: 'Setting win and loss limits helps manage your bankroll responsibly.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'craps_1',
      title: 'Craps Fundamentals',
      category: QuizCategory.craps,
      timeLimit: 600,
      passingScore: 70,
      questions: [
        Question(
          id: 'c1',
          question: 'What is the "come out roll" in Craps?',
          options: ['Last roll', 'First roll of new round', 'Any roll', 'Bonus roll'],
          correctAnswerIndex: 1,
          category: QuizCategory.craps,
          explanation: 'The come out roll is the first roll in a betting round at the craps table.',
          points: 10,
        ),
        Question(
          id: 'c2',
          question: 'What numbers are "craps" on come out roll?',
          options: ['2, 3, 12', '7, 11', '4, 5, 6', '8, 9, 10'],
          correctAnswerIndex: 0,
          category: QuizCategory.craps,
          explanation: 'Rolling 2, 3, or 12 on the come out roll is called craps and loses pass line bets.',
          points: 10,
        ),
        Question(
          id: 'c3',
          question: 'What is a "natural" in Craps?',
          options: ['2 or 3', '7 or 11', '4, 5, 6', 'Any double'],
          correctAnswerIndex: 1,
          category: QuizCategory.craps,
          explanation: 'A natural is rolling 7 or 11 on the come out roll, which wins pass line bets.',
          points: 10,
        ),
        Question(
          id: 'c4',
          question: 'What is the "point" in Craps?',
          options: ['First roll', 'Target number to roll again', 'Winning roll', 'Dealer marker'],
          correctAnswerIndex: 1,
          category: QuizCategory.craps,
          explanation: 'The point is established when 4, 5, 6, 8, 9, or 10 is rolled on come out.',
          points: 10,
        ),
        Question(
          id: 'c5',
          question: 'What is the house edge on pass line bet?',
          options: ['5.26%', '2.7%', '1.41%', '0.5%'],
          correctAnswerIndex: 2,
          category: QuizCategory.craps,
          explanation: 'The pass line bet has a house edge of 1.41%, one of the best bets in the casino.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'craps_2',
      title: 'Craps Betting Options',
      category: QuizCategory.craps,
      timeLimit: 600,
      passingScore: 70,
      questions: [
        Question(
          id: 'c6',
          question: 'What is a "Don\'t Pass" bet?',
          options: ['Opposite of pass line', 'Betting against shooter', 'Both A and B', 'Side bet'],
          correctAnswerIndex: 2,
          category: QuizCategory.craps,
          explanation: 'Don\'t Pass bets win when pass line loses (betting against the shooter).',
          points: 10,
        ),
        Question(
          id: 'c7',
          question: 'What are "odds bets" in Craps?',
          options: ['Side bet', 'Zero house edge backup bet', 'Prop bet', 'Center table bet'],
          correctAnswerIndex: 1,
          category: QuizCategory.craps,
          explanation: 'Odds bets are placed behind pass/don\'t pass and have zero house edge.',
          points: 10,
        ),
        Question(
          id: 'c8',
          question: 'What is a "Come bet"?',
          options: ['Same as pass line', 'Like pass line after point set', 'Prop bet', 'Field bet'],
          correctAnswerIndex: 1,
          category: QuizCategory.craps,
          explanation: 'Come bets work like pass line bets but can be made after point is established.',
          points: 10,
        ),
        Question(
          id: 'c9',
          question: 'What is a "Field bet"?',
          options: ['One-roll bet on 2,3,4,9,10,11,12', 'Point bet', 'Pass line type', 'Odds bet'],
          correctAnswerIndex: 0,
          category: QuizCategory.craps,
          explanation: 'Field bets win on next roll if 2, 3, 4, 9, 10, 11, or 12 is rolled.',
          points: 10,
        ),
        Question(
          id: 'c10',
          question: 'What are "Place bets"?',
          options: ['Betting specific number before 7', 'Field bets', 'Come bets', 'Prop bets'],
          correctAnswerIndex: 0,
          category: QuizCategory.craps,
          explanation: 'Place bets win if your chosen number (4,5,6,8,9,10) is rolled before a 7.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'craps_3',
      title: 'Craps Proposition Bets',
      category: QuizCategory.craps,
      timeLimit: 600,
      passingScore: 70,
      questions: [
        Question(
          id: 'c11',
          question: 'What is a "Hard Way" bet?',
          options: ['Doubles (4-4, 3-3)', 'Both dice same number', 'Difficult rolls', 'All of above'],
          correctAnswerIndex: 3,
          category: QuizCategory.craps,
          explanation: 'Hard way bets win when doubles hit before 7 or the number "easy way".',
          points: 10,
        ),
        Question(
          id: 'c12',
          question: 'What is an "Any Seven" bet?',
          options: ['Point is 7', 'Next roll is 7', 'Eventually 7', 'Seven before point'],
          correctAnswerIndex: 1,
          category: QuizCategory.craps,
          explanation: 'Any Seven is a one-roll bet that wins if next roll totals 7.',
          points: 10,
        ),
        Question(
          id: 'c13',
          question: 'Are proposition bets good bets?',
          options: ['Yes, high payouts', 'No, terrible house edge', 'Sometimes', 'Best bets'],
          correctAnswerIndex: 1,
          category: QuizCategory.craps,
          explanation: 'Proposition bets have very high house edges (10-16%) despite attractive payouts.',
          points: 10,
        ),
        Question(
          id: 'c14',
          question: 'What is "Snake Eyes"?',
          options: ['Double 1s', 'Total of 2', 'Both A and B', 'Dealer error'],
          correctAnswerIndex: 2,
          category: QuizCategory.craps,
          explanation: 'Snake Eyes refers to rolling double 1s (totaling 2).',
          points: 10,
        ),
        Question(
          id: 'c15',
          question: 'What is "Boxcars"?',
          options: ['Double 6s', 'Total of 12', 'Both A and B', 'Hard way 12'],
          correctAnswerIndex: 2,
          category: QuizCategory.craps,
          explanation: 'Boxcars refers to rolling double 6s (totaling 12).',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'craps_4',
      title: 'Craps Table Etiquette',
      category: QuizCategory.craps,
      timeLimit: 600,
      passingScore: 70,
      questions: [
        Question(
          id: 'c16',
          question: 'When should you not touch the dice?',
          options: ['When in play', 'Only when shooting', 'Never', 'Anytime'],
          correctAnswerIndex: 0,
          category: QuizCategory.craps,
          explanation: 'Never touch the dice when they\'re in play or being set up by the shooter.',
          points: 10,
        ),
        Question(
          id: 'c17',
          question: 'Should you say "seven" at craps table?',
          options: ['Yes', 'No, bad luck superstition', 'Only when betting', 'Dealer\'s job'],
          correctAnswerIndex: 1,
          category: QuizCategory.craps,
          explanation: 'Many players consider saying "seven" bad luck; use "it" or "devil" instead.',
          points: 10,
        ),
        Question(
          id: 'c18',
          question: 'Where should late bets be placed?',
          options: ['Throw on table', 'Hand to dealer with instruction', 'Anywhere', 'Can\'t bet late'],
          correctAnswerIndex: 1,
          category: QuizCategory.craps,
          explanation: 'Always hand chips to dealer and state your bet; don\'t toss onto table.',
          points: 10,
        ),
        Question(
          id: 'c19',
          question: 'Should you keep hands above table rail?',
          options: ['No', 'Yes, when dice in motion', 'Doesn\'t matter', 'Only for shooter'],
          correctAnswerIndex: 1,
          category: QuizCategory.craps,
          explanation: 'Keep hands up and out when dice are flying to avoid interfering.',
          points: 10,
        ),
        Question(
          id: 'c20',
          question: 'Is it okay to cheer at craps table?',
          options: ['No, too loud', 'Yes, encouraged!', 'Only when winning', 'Quiet tables only'],
          correctAnswerIndex: 1,
          category: QuizCategory.craps,
          explanation: 'Craps is a social, high-energy game where cheering and celebrating is welcome!',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'poker_3',
      title: 'Poker Tournament Strategy',
      category: QuizCategory.poker,
      timeLimit: 600,
      passingScore: 75,
      questions: [
        Question(
          id: 'p11',
          question: 'What is an "M-ratio" in tournaments?',
          options: ['Win rate', 'Stack size to blinds ratio', 'Tournament buy-in', 'Prize pool'],
          correctAnswerIndex: 1,
          category: QuizCategory.poker,
          explanation: 'M-ratio measures your stack size relative to blinds and antes, showing survival time.',
          points: 10,
        ),
        Question(
          id: 'p12',
          question: 'What is the "bubble" in a tournament?',
          options: ['Final table', 'Just before money', 'First elimination', 'Break time'],
          correctAnswerIndex: 1,
          category: QuizCategory.poker,
          explanation: 'The bubble is the point just before reaching the money, where next elimination is out.',
          points: 10,
        ),
        Question(
          id: 'p13',
          question: 'What is ICM in poker?',
          options: ['International Casino Management', 'Independent Chip Model', 'Initial Card Method', 'In-game Cash Metric'],
          correctAnswerIndex: 1,
          category: QuizCategory.poker,
          explanation: 'ICM (Independent Chip Model) calculates tournament equity based on chip stacks.',
          points: 10,
        ),
        Question(
          id: 'p14',
          question: 'What is a "satellite" tournament?',
          options: ['Online only', 'Winner gets bigger tournament entry', 'Small buy-in', 'Practice tournament'],
          correctAnswerIndex: 1,
          category: QuizCategory.poker,
          explanation: 'A satellite is a tournament where winners earn entry into a larger, more expensive event.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'poker_4',
      title: 'Poker Hand Rankings',
      category: QuizCategory.poker,
      timeLimit: 600,
      passingScore: 70,
      questions: [
        Question(
          id: 'p15',
          question: 'What is the rarest hand in poker?',
          options: ['Four of a kind', 'Straight flush', 'Royal flush', 'Full house'],
          correctAnswerIndex: 2,
          category: QuizCategory.poker,
          explanation: 'A royal flush (10-J-Q-K-A of same suit) is the rarest and best possible hand.',
          points: 10,
        ),
        Question(
          id: 'p16',
          question: 'What beats a straight?',
          options: ['Three of a kind', 'Flush', 'Two pair', 'High card'],
          correctAnswerIndex: 1,
          category: QuizCategory.poker,
          explanation: 'A flush (five cards of same suit) beats a straight.',
          points: 10,
        ),
        Question(
          id: 'p17',
          question: 'What is the lowest possible straight?',
          options: ['A-2-3-4-5', '2-3-4-5-6', 'A-K-Q-J-10', '5-6-7-8-9'],
          correctAnswerIndex: 0,
          category: QuizCategory.poker,
          explanation: 'A-2-3-4-5 is the lowest straight, called a "wheel" or "bicycle".',
          points: 10,
        ),
        Question(
          id: 'p18',
          question: 'What is a "boat" in poker?',
          options: ['Full house', 'Flush', 'Straight', 'Royal flush'],
          correctAnswerIndex: 0,
          category: QuizCategory.poker,
          explanation: 'A "boat" is slang for a full house (three of a kind plus a pair).',
          points: 10,
        ),
        Question(
          id: 'p19',
          question: 'If two players have a flush, who wins?',
          options: ['Split pot always', 'Highest card in flush', 'Most cards of same suit', 'First to bet'],
          correctAnswerIndex: 1,
          category: QuizCategory.poker,
          explanation: 'When both have flushes, the player with the highest card in their flush wins.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'poker_5',
      title: 'Poker Betting Rounds',
      category: QuizCategory.poker,
      timeLimit: 600,
      passingScore: 70,
      questions: [
        Question(
          id: 'p20',
          question: 'What is the "big blind"?',
          options: ['Largest bet', 'Forced bet from button', 'Forced bet two seats left of dealer', 'Optional bet'],
          correctAnswerIndex: 2,
          category: QuizCategory.poker,
          explanation: 'The big blind is a forced bet made by the player two seats to the left of the dealer.',
          points: 10,
        ),
        Question(
          id: 'p21',
          question: 'What does "check" mean in poker?',
          options: ['Fold hand', 'Match bet', 'Pass action without betting', 'Raise bet'],
          correctAnswerIndex: 2,
          category: QuizCategory.poker,
          explanation: 'Checking means passing the action to the next player without placing a bet.',
          points: 10,
        ),
        Question(
          id: 'p22',
          question: 'What is a "raise"?',
          options: ['Fold cards', 'Match current bet', 'Increase the current bet', 'Check'],
          correctAnswerIndex: 2,
          category: QuizCategory.poker,
          explanation: 'A raise means increasing the current bet, forcing others to match the new amount.',
          points: 10,
        ),
        Question(
          id: 'p23',
          question: 'What is the "river" in poker?',
          options: ['First card', 'Fourth community card', 'Fifth and final community card', 'Third card'],
          correctAnswerIndex: 2,
          category: QuizCategory.poker,
          explanation: 'The river is the fifth and final community card dealt in Texas Hold\'em.',
          points: 10,
        ),
        Question(
          id: 'p24',
          question: 'What is "checking down"?',
          options: ['Folding quickly', 'All players check to showdown', 'Raising aggressively', 'Bluffing'],
          correctAnswerIndex: 1,
          category: QuizCategory.poker,
          explanation: 'Checking down means all remaining players check through to showdown without betting.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'poker_6',
      title: 'Poker Psychology',
      category: QuizCategory.poker,
      timeLimit: 600,
      passingScore: 75,
      questions: [
        Question(
          id: 'p25',
          question: 'What is a "tell" in poker?',
          options: ['Revealing cards', 'Physical or behavioral clue', 'Verbal declaration', 'Betting pattern'],
          correctAnswerIndex: 1,
          category: QuizCategory.poker,
          explanation: 'A tell is an unconscious physical or behavioral action that reveals information about your hand.',
          points: 10,
        ),
        Question(
          id: 'p26',
          question: 'What is "tilting" in poker?',
          options: ['Winning streak', 'Playing emotionally after bad beat', 'Aggressive strategy', 'Tournament position'],
          correctAnswerIndex: 1,
          category: QuizCategory.poker,
          explanation: 'Tilting means playing emotionally and irrationally, usually after losing a big hand.',
          points: 10,
        ),
        Question(
          id: 'p27',
          question: 'What is "table image"?',
          options: ['Table design', 'How others perceive your play', 'Seating position', 'Chip stack size'],
          correctAnswerIndex: 1,
          category: QuizCategory.poker,
          explanation: 'Table image is how other players perceive your playing style and tendencies.',
          points: 10,
        ),
        Question(
          id: 'p28',
          question: 'What is a "poker face"?',
          options: ['Smiling', 'Neutral expression hiding emotions', 'Angry look', 'Talking strategy'],
          correctAnswerIndex: 1,
          category: QuizCategory.poker,
          explanation: 'A poker face is maintaining a neutral expression to avoid giving away information.',
          points: 10,
        ),
        Question(
          id: 'p29',
          question: 'What is "value betting"?',
          options: ['Betting your best hands', 'Betting for information', 'Bluffing', 'Min-raising'],
          correctAnswerIndex: 0,
          category: QuizCategory.poker,
          explanation: 'Value betting means betting strong hands to get paid by weaker hands.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'poker_7',
      title: 'Omaha Poker Basics',
      category: QuizCategory.poker,
      timeLimit: 600,
      passingScore: 70,
      questions: [
        Question(
          id: 'p30',
          question: 'How many hole cards do you get in Omaha?',
          options: ['2', '3', '4', '5'],
          correctAnswerIndex: 2,
          category: QuizCategory.poker,
          explanation: 'In Omaha poker, each player receives four hole cards instead of two.',
          points: 10,
        ),
        Question(
          id: 'p31',
          question: 'How many hole cards must you use in Omaha?',
          options: ['0', '1', '2', '4'],
          correctAnswerIndex: 2,
          category: QuizCategory.poker,
          explanation: 'In Omaha, you must use exactly two of your four hole cards to make your hand.',
          points: 10,
        ),
        Question(
          id: 'p32',
          question: 'What is PLO in poker?',
          options: ['Pot Limit Omaha', 'Player League Online', 'Pot Limit Only', 'Professional Level Omaha'],
          correctAnswerIndex: 0,
          category: QuizCategory.poker,
          explanation: 'PLO stands for Pot Limit Omaha, where maximum bet is the current pot size.',
          points: 10,
        ),
        Question(
          id: 'p33',
          question: 'How many community cards in Omaha?',
          options: ['3', '4', '5', '6'],
          correctAnswerIndex: 2,
          category: QuizCategory.poker,
          explanation: 'Omaha uses the same five community cards as Texas Hold\'em.',
          points: 10,
        ),
        Question(
          id: 'p34',
          question: 'What is Omaha Hi-Lo?',
          options: ['High stakes only', 'Split pot between best and worst hands', 'Tournament format', 'Betting structure'],
          correctAnswerIndex: 1,
          category: QuizCategory.poker,
          explanation: 'Omaha Hi-Lo splits the pot between the highest hand and lowest qualifying hand.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'blackjack_3',
      title: 'Card Counting Basics',
      category: QuizCategory.blackjack,
      timeLimit: 600,
      passingScore: 80,
      questions: [
        Question(
          id: 'b11',
          question: 'What is the Hi-Lo counting system?',
          options: ['Betting strategy', 'Card tracking method', 'Shuffle tracking', 'Dealer system'],
          correctAnswerIndex: 1,
          category: QuizCategory.blackjack,
          explanation: 'Hi-Lo is a balanced card counting system assigning +1, 0, or -1 to cards.',
          points: 10,
        ),
        Question(
          id: 'b12',
          question: 'What is a "true count"?',
          options: ['Actual count', 'Running count divided by decks remaining', 'Win percentage', 'Dealer count'],
          correctAnswerIndex: 1,
          category: QuizCategory.blackjack,
          explanation: 'True count adjusts the running count for the number of decks remaining.',
          points: 10,
        ),
        Question(
          id: 'b13',
          question: 'When is the deck "rich" in card counting?',
          options: ['Many low cards left', 'Many high cards left', 'Equal cards', 'After shuffle'],
          correctAnswerIndex: 1,
          category: QuizCategory.blackjack,
          explanation: 'A deck is "rich" when there are more high cards (10s, faces, aces) remaining.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'blackjack_4',
      title: 'Blackjack Variations',
      category: QuizCategory.blackjack,
      timeLimit: 600,
      passingScore: 70,
      questions: [
        Question(
          id: 'b14',
          question: 'What is Spanish 21?',
          options: ['Blackjack in Spain', 'Deck without 10s', 'Fast version', 'Tournament format'],
          correctAnswerIndex: 1,
          category: QuizCategory.blackjack,
          explanation: 'Spanish 21 is played with a 48-card deck (all four 10s removed from each deck).',
          points: 10,
        ),
        Question(
          id: 'b15',
          question: 'What is Blackjack Switch?',
          options: ['Dealer switches', 'Players switch two hands', 'Card switching', 'Bet switching'],
          correctAnswerIndex: 1,
          category: QuizCategory.blackjack,
          explanation: 'In Blackjack Switch, players play two hands and can switch the top cards between them.',
          points: 10,
        ),
        Question(
          id: 'b16',
          question: 'What is Double Exposure Blackjack?',
          options: ['Two decks', 'Both dealer cards face up', 'Double bets', 'Two dealers'],
          correctAnswerIndex: 1,
          category: QuizCategory.blackjack,
          explanation: 'Double Exposure shows both dealer cards face up, but ties go to the dealer.',
          points: 10,
        ),
        Question(
          id: 'b17',
          question: 'What is Pontoon?',
          options: ['British blackjack variant', 'French version', 'Asian variant', 'Online only'],
          correctAnswerIndex: 0,
          category: QuizCategory.blackjack,
          explanation: 'Pontoon is a British variant of blackjack with different terminology and rules.',
          points: 10,
        ),
        Question(
          id: 'b18',
          question: 'What is a "Charlie" rule in blackjack?',
          options: ['Named dealer', 'Auto-win with X cards under 21', 'Betting system', 'Insurance type'],
          correctAnswerIndex: 1,
          category: QuizCategory.blackjack,
          explanation: 'A Charlie rule (5-card Charlie, etc.) means you auto-win with that many cards under 21.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'blackjack_5',
      title: 'Blackjack Side Bets',
      category: QuizCategory.blackjack,
      timeLimit: 600,
      passingScore: 70,
      questions: [
        Question(
          id: 'b19',
          question: 'What is "Perfect Pairs" side bet?',
          options: ['Pairs in hand', 'First two cards are a pair', 'Dealer pairs', 'Any two pairs'],
          correctAnswerIndex: 1,
          category: QuizCategory.blackjack,
          explanation: 'Perfect Pairs bets pay if your first two cards are a pair, with higher payouts for suited pairs.',
          points: 10,
        ),
        Question(
          id: 'b20',
          question: 'What is "21+3" side bet?',
          options: ['Total over 21', 'Poker hand from 3 cards', 'Three cards equal 21', 'Betting on 21'],
          correctAnswerIndex: 1,
          category: QuizCategory.blackjack,
          explanation: '21+3 combines your two cards with dealer\'s up card to form a poker hand.',
          points: 10,
        ),
        Question(
          id: 'b21',
          question: 'What is "Lucky Ladies" side bet?',
          options: ['Female dealers', 'First hand totals 20', 'Queen pairs', 'Women players'],
          correctAnswerIndex: 1,
          category: QuizCategory.blackjack,
          explanation: 'Lucky Ladies pays when your first two cards total 20, with bonuses for Queen pairs.',
          points: 10,
        ),
        Question(
          id: 'b22',
          question: 'Are side bets generally good bets?',
          options: ['Yes, best odds', 'No, high house edge', 'Same as main bet', 'Only for pros'],
          correctAnswerIndex: 1,
          category: QuizCategory.blackjack,
          explanation: 'Side bets typically have much higher house edges than the main blackjack game.',
          points: 10,
        ),
        Question(
          id: 'b23',
          question: 'What is "Bust It" side bet?',
          options: ['Player busting', 'Dealer busting', 'Both bust', 'Neither bust'],
          correctAnswerIndex: 1,
          category: QuizCategory.blackjack,
          explanation: 'Bust It side bet pays when the dealer busts, with higher payouts for more cards.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'blackjack_6',
      title: 'Blackjack Etiquette',
      category: QuizCategory.blackjack,
      timeLimit: 600,
      passingScore: 70,
      questions: [
        Question(
          id: 'b24',
          question: 'How should you signal "hit" in hand-held games?',
          options: ['Tap table', 'Scratch cards toward you', 'Say "hit"', 'Wave hand'],
          correctAnswerIndex: 1,
          category: QuizCategory.blackjack,
          explanation: 'In hand-held games, scratch your cards toward you on the felt to signal hit.',
          points: 10,
        ),
        Question(
          id: 'b25',
          question: 'How should you signal "stand"?',
          options: ['Say "stand"', 'Wave hand horizontally', 'Slide cards under chips', 'Nod head'],
          correctAnswerIndex: 2,
          category: QuizCategory.blackjack,
          explanation: 'In hand-held games, slide your cards face-down under your chips to stand.',
          points: 10,
        ),
        Question(
          id: 'b26',
          question: 'Should you touch chips after cards are dealt?',
          options: ['Yes, always', 'No, never', 'Only when doubling', 'Only when winning'],
          correctAnswerIndex: 2,
          category: QuizCategory.blackjack,
          explanation: 'Never touch chips after cards are dealt except when doubling down or splitting.',
          points: 10,
        ),
        Question(
          id: 'b27',
          question: 'Should you give advice to other players?',
          options: ['Yes, help them', 'No, it\'s rude', 'Only if asked', 'Only to beginners'],
          correctAnswerIndex: 1,
          category: QuizCategory.blackjack,
          explanation: 'It\'s generally considered rude to give unsolicited advice at blackjack tables.',
          points: 10,
        ),
        Question(
          id: 'b28',
          question: 'Is it appropriate to tip the dealer?',
          options: ['Never', 'Yes, customary', 'Only when winning big', 'Only in private games'],
          correctAnswerIndex: 1,
          category: QuizCategory.blackjack,
          explanation: 'Tipping dealers is customary, either by making a bet for them or handing chips.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'slots_3',
      title: 'Modern Slot Features',
      category: QuizCategory.slots,
      timeLimit: 600,
      passingScore: 70,
      questions: [
        Question(
          id: 's11',
          question: 'What are "cascading reels"?',
          options: ['Reels fall down', 'Winning symbols disappear and new ones drop', 'Bonus feature', 'Free spins'],
          correctAnswerIndex: 1,
          category: QuizCategory.slots,
          explanation: 'Cascading reels remove winning symbols and drop new ones for potential consecutive wins.',
          points: 10,
        ),
        Question(
          id: 's12',
          question: 'What is a "megaways" slot?',
          options: ['Big jackpot', 'Variable number of symbols per reel', 'Multiple bonuses', 'Wide screen'],
          correctAnswerIndex: 1,
          category: QuizCategory.slots,
          explanation: 'Megaways slots have varying symbols per reel each spin, creating thousands of ways to win.',
          points: 10,
        ),
        Question(
          id: 's13',
          question: 'What are "expanding wilds"?',
          options: ['Wilds that cover entire reel', 'More wild symbols', 'Bonus wilds', 'Progressive wilds'],
          correctAnswerIndex: 0,
          category: QuizCategory.slots,
          explanation: 'Expanding wilds grow to cover an entire reel when they appear.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'slots_4',
      title: 'Slot Machine Myths',
      category: QuizCategory.slots,
      timeLimit: 600,
      passingScore: 70,
      questions: [
        Question(
          id: 's14',
          question: 'Do slots pay more when casino is busy?',
          options: ['Yes, to attract players', 'No, RNG is constant', 'Only on weekends', 'Yes, at night'],
          correctAnswerIndex: 1,
          category: QuizCategory.slots,
          explanation: 'Slots use RNG that is constant regardless of time, crowd, or any external factors.',
          points: 10,
        ),
        Question(
          id: 's15',
          question: 'Can you predict when a slot will hit?',
          options: ['Yes, watch patterns', 'No, completely random', 'Yes, count spins', 'Yes, with systems'],
          correctAnswerIndex: 1,
          category: QuizCategory.slots,
          explanation: 'Each spin is independent and random; past results cannot predict future outcomes.',
          points: 10,
        ),
        Question(
          id: 's16',
          question: 'Do slots near entrances pay better?',
          options: ['Yes, to attract players', 'No, urban myth', 'Sometimes', 'Only in Vegas'],
          correctAnswerIndex: 1,
          category: QuizCategory.slots,
          explanation: 'This is a common myth; slot placement does not affect payout rates.',
          points: 10,
        ),
        Question(
          id: 's17',
          question: 'Does using player card reduce payouts?',
          options: ['Yes, casino tracks you', 'No, no effect on RNG', 'Sometimes', 'Only for high rollers'],
          correctAnswerIndex: 1,
          category: QuizCategory.slots,
          explanation: 'Player cards only track play for rewards; they cannot affect the RNG or payouts.',
          points: 10,
        ),
        Question(
          id: 's18',
          question: 'Are "hot" and "cold" machines real?',
          options: ['Yes, avoid cold ones', 'No, randomness creates streaks', 'Yes, pick hot ones', 'Only for progressives'],
          correctAnswerIndex: 1,
          category: QuizCategory.slots,
          explanation: 'Random results naturally create streaks, but machines are never "due" to pay.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'slots_5',
      title: 'Progressive Jackpots',
      category: QuizCategory.slots,
      timeLimit: 600,
      passingScore: 70,
      questions: [
        Question(
          id: 's19',
          question: 'What is a standalone progressive?',
          options: ['Not connected to network', 'Single machine jackpot', 'High volatility', 'New machine type'],
          correctAnswerIndex: 1,
          category: QuizCategory.slots,
          explanation: 'Standalone progressives have jackpots that grow only from play on that one machine.',
          points: 10,
        ),
        Question(
          id: 's20',
          question: 'What is a wide-area progressive?',
          options: ['Big screens', 'Linked across multiple casinos', 'High RTP', 'Bonus feature'],
          correctAnswerIndex: 1,
          category: QuizCategory.slots,
          explanation: 'Wide-area progressives link machines across multiple casinos for huge jackpots.',
          points: 10,
        ),
        Question(
          id: 's21',
          question: 'Must you bet max to win progressive?',
          options: ['Always yes', 'Usually yes', 'Never', 'Depends on game'],
          correctAnswerIndex: 3,
          category: QuizCategory.slots,
          explanation: 'Some progressives require max bet, others don\'t; always check the game rules.',
          points: 10,
        ),
        Question(
          id: 's22',
          question: 'What is a "must-hit-by" progressive?',
          options: ['Random jackpot', 'Guaranteed to hit before set amount', 'Time-limited', 'Tournament style'],
          correctAnswerIndex: 1,
          category: QuizCategory.slots,
          explanation: 'Must-hit-by progressives are guaranteed to pay before reaching a specified amount.',
          points: 10,
        ),
        Question(
          id: 's23',
          question: 'What happens to progressive after jackpot?',
          options: ['Stops growing', 'Resets to base amount', 'Pays smaller amounts', 'Machine closes'],
          correctAnswerIndex: 1,
          category: QuizCategory.slots,
          explanation: 'After a progressive jackpot hits, it resets to a predetermined base amount.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'slots_6',
      title: 'Slot Terminology',
      category: QuizCategory.slots,
      timeLimit: 600,
      passingScore: 70,
      questions: [
        Question(
          id: 's24',
          question: 'What is a "multiplier"?',
          options: ['More reels', 'Increases win amount by X times', 'Bonus round', 'Extra spins'],
          correctAnswerIndex: 1,
          category: QuizCategory.slots,
          explanation: 'Multipliers increase your win by a specified factor (2x, 3x, etc.).',
          points: 10,
        ),
        Question(
          id: 's25',
          question: 'What is "gamble feature"?',
          options: ['Risk winnings to double', 'Bonus game', 'Free spins', 'Auto play'],
          correctAnswerIndex: 0,
          category: QuizCategory.slots,
          explanation: 'Gamble features let you risk your win for a chance to double or increase it.',
          points: 10,
        ),
        Question(
          id: 's26',
          question: 'What are "sticky wilds"?',
          options: ['Wilds that remain for multiple spins', 'Larger wilds', 'Multiplier wilds', 'Random wilds'],
          correctAnswerIndex: 0,
          category: QuizCategory.slots,
          explanation: 'Sticky wilds remain in position for several spins, increasing win potential.',
          points: 10,
        ),
        Question(
          id: 's27',
          question: 'What is "autoplay"?',
          options: ['Demo mode', 'Automatic spin feature', 'AI player', 'Tutorial mode'],
          correctAnswerIndex: 1,
          category: QuizCategory.slots,
          explanation: 'Autoplay automatically spins the reels for a set number of times.',
          points: 10,
        ),
        Question(
          id: 's28',
          question: 'What is a "bonus buy"?',
          options: ['Extra credits', 'Purchase direct access to bonus', 'VIP feature', 'Insurance bet'],
          correctAnswerIndex: 1,
          category: QuizCategory.slots,
          explanation: 'Bonus buy features let you pay to directly trigger the bonus round.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'roulette_3',
      title: 'Roulette Betting Systems',
      category: QuizCategory.roulette,
      timeLimit: 600,
      passingScore: 70,
      questions: [
        Question(
          id: 'r11',
          question: 'What is the Martingale betting system?',
          options: ['Bet same amount', 'Double bet after loss', 'Decrease after win', 'Random betting'],
          correctAnswerIndex: 1,
          category: QuizCategory.roulette,
          explanation: 'Martingale system doubles your bet after each loss to recover previous losses.',
          points: 10,
        ),
        Question(
          id: 'r12',
          question: 'What is the Fibonacci betting system?',
          options: ['Mathematical sequence betting', 'Even money only', 'Progressive jackpot', 'Dealer system'],
          correctAnswerIndex: 0,
          category: QuizCategory.roulette,
          explanation: 'Fibonacci system uses the famous number sequence (1,1,2,3,5,8...) for bet sizing.',
          points: 10,
        ),
        Question(
          id: 'r13',
          question: 'What is the D\'Alembert system?',
          options: ['Card counting', 'Increase by one after loss, decrease after win', 'European only', 'Color betting'],
          correctAnswerIndex: 1,
          category: QuizCategory.roulette,
          explanation: 'D\'Alembert system increases bets by one unit after loss, decreases by one after win.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'roulette_4',
      title: 'Roulette Wheel Mechanics',
      category: QuizCategory.roulette,
      timeLimit: 600,
      passingScore: 70,
      questions: [
        Question(
          id: 'r14',
          question: 'What direction does the roulette wheel spin?',
          options: ['Always clockwise', 'Always counter-clockwise', 'Alternates direction', 'Random'],
          correctAnswerIndex: 2,
          category: QuizCategory.roulette,
          explanation: 'Dealers alternate the wheel direction between spins for fairness and randomness.',
          points: 10,
        ),
        Question(
          id: 'r15',
          question: 'What are the "neighbors" in roulette?',
          options: ['Players next to you', 'Adjacent numbers on wheel', 'Consecutive bets', 'Table sections'],
          correctAnswerIndex: 1,
          category: QuizCategory.roulette,
          explanation: 'Neighbors are numbers adjacent to each other on the physical roulette wheel.',
          points: 10,
        ),
        Question(
          id: 'r16',
          question: 'What is a "biased wheel"?',
          options: ['Defective wheel favoring certain numbers', 'European wheel', 'Tilted table', 'Fast spin'],
          correctAnswerIndex: 0,
          category: QuizCategory.roulette,
          explanation: 'A biased wheel has imperfections causing certain numbers to hit more frequently.',
          points: 10,
        ),
        Question(
          id: 'r17',
          question: 'What is the "ball track"?',
          options: ['Betting area', 'Rim where ball spins', 'Wheel center', 'Number pockets'],
          correctAnswerIndex: 1,
          category: QuizCategory.roulette,
          explanation: 'The ball track is the outer rim of the wheel where the ball initially spins.',
          points: 10,
        ),
        Question(
          id: 'r18',
          question: 'Are roulette outcomes predictable?',
          options: ['Yes, with math', 'No, completely random', 'Only on biased wheels', 'Only with computers'],
          correctAnswerIndex: 1,
          category: QuizCategory.roulette,
          explanation: 'On fair wheels, each spin is an independent random event and cannot be predicted.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'roulette_5',
      title: 'French Roulette Rules',
      category: QuizCategory.roulette,
      timeLimit: 600,
      passingScore: 70,
      questions: [
        Question(
          id: 'r19',
          question: 'What is "La Partage" rule?',
          options: ['Split winnings', 'Get half bet back on zero', 'Share with dealer', 'Bonus bet'],
          correctAnswerIndex: 1,
          category: QuizCategory.roulette,
          explanation: 'La Partage returns half your even-money bet when zero hits, reducing house edge.',
          points: 10,
        ),
        Question(
          id: 'r20',
          question: 'What is a "Voisins du Zero" bet?',
          options: ['Zero neighbors', '17 numbers around zero on wheel', 'Betting on zero', 'Zero section'],
          correctAnswerIndex: 1,
          category: QuizCategory.roulette,
          explanation: 'Voisins du Zero covers 17 numbers on the wheel near zero, using 9 chips.',
          points: 10,
        ),
        Question(
          id: 'r21',
          question: 'What is "Tiers du Cylindre"?',
          options: ['Third of wheel', '12 numbers opposite zero', 'High bets', 'Dozen bet'],
          correctAnswerIndex: 1,
          category: QuizCategory.roulette,
          explanation: 'Tiers covers 12 numbers opposite zero on the wheel, using 6 chips.',
          points: 10,
        ),
        Question(
          id: 'r22',
          question: 'What is "Orphelins" bet?',
          options: ['Orphan numbers', '8 numbers not in Voisins or Tiers', 'Corner bet', 'Split bet'],
          correctAnswerIndex: 1,
          category: QuizCategory.roulette,
          explanation: 'Orphelins covers 8 "orphan" numbers not in Voisins or Tiers sections.',
          points: 10,
        ),
        Question(
          id: 'r23',
          question: 'What makes French roulette different?',
          options: ['French dealers', 'La Partage and En Prison rules', 'Different numbers', 'Faster play'],
          correctAnswerIndex: 1,
          category: QuizCategory.roulette,
          explanation: 'French roulette features La Partage and En Prison rules that lower the house edge.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'roulette_6',
      title: 'Roulette Odds & Payouts',
      category: QuizCategory.roulette,
      timeLimit: 600,
      passingScore: 75,
      questions: [
        Question(
          id: 'r24',
          question: 'What is the payout for a split bet?',
          options: ['11:1', '17:1', '8:1', '35:1'],
          correctAnswerIndex: 1,
          category: QuizCategory.roulette,
          explanation: 'A split bet (two numbers) pays 17:1 when it hits.',
          points: 10,
        ),
        Question(
          id: 'r25',
          question: 'What is the payout for a column bet?',
          options: ['1:1', '2:1', '3:1', '5:1'],
          correctAnswerIndex: 1,
          category: QuizCategory.roulette,
          explanation: 'Column bets cover 12 numbers and pay 2:1.',
          points: 10,
        ),
        Question(
          id: 'r26',
          question: 'What is the probability of hitting a single number?',
          options: ['1/36', '1/37 (European)', '1/38 (American)', 'Both B and C'],
          correctAnswerIndex: 3,
          category: QuizCategory.roulette,
          explanation: 'European roulette is 1/37, American is 1/38 due to the double zero.',
          points: 10,
        ),
        Question(
          id: 'r27',
          question: 'What is the house edge on a "basket bet"?',
          options: ['2.7%', '5.26%', '7.89%', '10%'],
          correctAnswerIndex: 2,
          category: QuizCategory.roulette,
          explanation: 'The basket bet (0-00-1-2-3) has the worst odds at 7.89% house edge.',
          points: 10,
        ),
        Question(
          id: 'r28',
          question: 'Which bet has the best odds in roulette?',
          options: ['Straight up', 'Even money bets', 'Dozens', 'All same odds'],
          correctAnswerIndex: 3,
          category: QuizCategory.roulette,
          explanation: 'Except for the basket bet, all bets have the same house edge in roulette.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'general_2',
      title: 'Casino Mathematics',
      category: QuizCategory.general,
      timeLimit: 900,
      passingScore: 75,
      questions: [
        Question(
          id: 'g8',
          question: 'What is "expected value" (EV) in gambling?',
          options: ['Win amount', 'Average long-term result', 'Jackpot size', 'House edge'],
          correctAnswerIndex: 1,
          category: QuizCategory.general,
          explanation: 'Expected value is the average amount you can expect to win or lose per bet over time.',
          points: 10,
        ),
        Question(
          id: 'g9',
          question: 'What is "variance" in casino games?',
          options: ['Game speed', 'Result fluctuation from average', 'House advantage', 'Bet limits'],
          correctAnswerIndex: 1,
          category: QuizCategory.general,
          explanation: 'Variance measures how much results deviate from expected value in the short term.',
          points: 10,
        ),
        Question(
          id: 'g10',
          question: 'What is "standard deviation"?',
          options: ['Normal betting', 'Measure of result spread', 'Average win', 'Loss limit'],
          correctAnswerIndex: 1,
          category: QuizCategory.general,
          explanation: 'Standard deviation quantifies the amount of variation in outcomes from the mean.',
          points: 10,
        ),
        Question(
          id: 'g11',
          question: 'What is the "law of large numbers"?',
          options: ['Big bets win more', 'Results approach expected value over time', 'More players = better odds', 'Jackpot probability'],
          correctAnswerIndex: 1,
          category: QuizCategory.general,
          explanation: 'The law states that actual results converge to theoretical probability over many trials.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'general_3',
      title: 'Casino History',
      category: QuizCategory.general,
      timeLimit: 900,
      passingScore: 70,
      questions: [
        Question(
          id: 'g12',
          question: 'Where was the first casino opened?',
          options: ['Las Vegas', 'Monte Carlo', 'Venice, Italy', 'Atlantic City'],
          correctAnswerIndex: 2,
          category: QuizCategory.general,
          explanation: 'The Casino di Venezia opened in Venice, Italy in 1638.',
          points: 10,
        ),
        Question(
          id: 'g13',
          question: 'When did Las Vegas become a gambling destination?',
          options: ['1800s', '1930s-1940s', '1960s', '1990s'],
          correctAnswerIndex: 1,
          category: QuizCategory.general,
          explanation: 'Las Vegas legalized gambling in 1931 and grew as a destination in the 1940s.',
          points: 10,
        ),
        Question(
          id: 'g14',
          question: 'What does "Monte Carlo" mean in gambling?',
          options: ['Famous casino location', 'Betting system', 'Card game', 'Chip value'],
          correctAnswerIndex: 0,
          category: QuizCategory.general,
          explanation: 'Monte Carlo is a district in Monaco famous for its luxurious casino since 1863.',
          points: 10,
        ),
        Question(
          id: 'g15',
          question: 'What was "The Rat Pack"?',
          options: ['Casino owners', 'Famous Vegas entertainers', 'Card counters', 'Security team'],
          correctAnswerIndex: 1,
          category: QuizCategory.general,
          explanation: 'The Rat Pack (Sinatra, Martin, Davis Jr.) were iconic Las Vegas entertainers in the 1960s.',
          points: 10,
        ),
        Question(
          id: 'g16',
          question: 'When did online gambling begin?',
          options: ['1980s', 'Mid-1990s', '2000s', '2010s'],
          correctAnswerIndex: 1,
          category: QuizCategory.general,
          explanation: 'The first online casinos launched in the mid-1990s with the internet boom.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'general_4',
      title: 'Responsible Gambling',
      category: QuizCategory.general,
      timeLimit: 900,
      passingScore: 80,
      questions: [
        Question(
          id: 'g17',
          question: 'What is problem gambling?',
          options: ['Losing money', 'Uncontrollable urge to gamble despite harm', 'Bad luck', 'Playing daily'],
          correctAnswerIndex: 1,
          category: QuizCategory.general,
          explanation: 'Problem gambling is the inability to control gambling despite negative consequences.',
          points: 10,
        ),
        Question(
          id: 'g18',
          question: 'What is a gambling self-exclusion program?',
          options: ['VIP club', 'Ban yourself from casinos', 'Loyalty program', 'Private tables'],
          correctAnswerIndex: 1,
          category: QuizCategory.general,
          explanation: 'Self-exclusion programs allow people to voluntarily ban themselves from gambling venues.',
          points: 10,
        ),
        Question(
          id: 'g19',
          question: 'Should you gamble to make money?',
          options: ['Yes, it\'s profitable', 'No, for entertainment only', 'Sometimes', 'Only if skilled'],
          correctAnswerIndex: 1,
          category: QuizCategory.general,
          explanation: 'Gambling should be entertainment; the house always has an edge in the long run.',
          points: 10,
        ),
        Question(
          id: 'g20',
          question: 'What is "chasing losses"?',
          options: ['Good strategy', 'Dangerous behavior increasing bets after loss', 'Winning strategy', 'Card counting'],
          correctAnswerIndex: 1,
          category: QuizCategory.general,
          explanation: 'Chasing losses means betting more to recover previous losses, often leading to bigger losses.',
          points: 10,
        ),
        Question(
          id: 'g21',
          question: 'What percentage of gamblers develop problems?',
          options: ['50%', '25%', '1-3%', 'Everyone'],
          correctAnswerIndex: 2,
          category: QuizCategory.general,
          explanation: 'Research shows approximately 1-3% of gamblers develop gambling problems.',
          points: 10,
        ),
      ],
    ),
    Quiz(
      id: 'general_5',
      title: 'Casino Operations',
      category: QuizCategory.general,
      timeLimit: 900,
      passingScore: 70,
      questions: [
        Question(
          id: 'g22',
          question: 'What is casino surveillance called?',
          options: ['Security', 'The Eye in the Sky', 'Watchers', 'Casino police'],
          correctAnswerIndex: 1,
          category: QuizCategory.general,
          explanation: '"Eye in the Sky" refers to casino surveillance cameras and monitoring rooms.',
          points: 10,
        ),
        Question(
          id: 'g23',
          question: 'Why don\'t casinos have clocks?',
          options: ['Broken', 'Keep players unaware of time', 'Style choice', 'Regulations'],
          correctAnswerIndex: 1,
          category: QuizCategory.general,
          explanation: 'Casinos avoid clocks to prevent players from tracking time and leaving.',
          points: 10,
        ),
        Question(
          id: 'g24',
          question: 'What is a "pit boss"?',
          options: ['Dealer manager', 'Supervisor overseeing table games', 'Security chief', 'Casino owner'],
          correctAnswerIndex: 1,
          category: QuizCategory.general,
          explanation: 'A pit boss supervises dealers and table games in a specific casino section.',
          points: 10,
        ),
        Question(
          id: 'g25',
          question: 'What are casino chips made of?',
          options: ['Plastic', 'Clay composite', 'Wood', 'Metal'],
          correctAnswerIndex: 1,
          category: QuizCategory.general,
          explanation: 'Modern casino chips are made from clay composite materials for durability and feel.',
          points: 10,
        ),
        Question(
          id: 'g26',
          question: 'Why do casinos pump oxygen?',
          options: ['They do', 'Myth - they don\'t', 'Only high stakes areas', 'Fire code'],
          correctAnswerIndex: 1,
          category: QuizCategory.general,
          explanation: 'This is a common myth; casinos don\'t pump oxygen (it would be a fire hazard).',
          points: 10,
        ),
      ],
    ),
  ];
}
