import '../models/quiz.dart';

// NEW CATEGORY: Casino Math - Part 6
final List<Quiz> casinoMathQuizzes = [
  // Beginner
  Quiz(
    id: 'casino_math_beginner_1',
    title: 'Basic Casino Mathematics',
    category: QuizCategory.casinoMath,
    difficulty: DifficultyLevel.beginner,
    timeLimit: 480,
    passingScore: 70,
    questions: [
      Question(
        id: 'cm_b1_1',
        question: 'What is "house edge" in casino games?',
        options: ['Building advantage', 'Mathematical advantage casino has over players', 'Table location', 'Dealer skill'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: 'House edge is the mathematical advantage the casino has over players in any given game.',
        points: 10,
      ),
      Question(
        id: 'cm_b1_2',
        question: 'If a player bets \$100 at even money and wins, how much do they receive total?',
        options: ['\$100', '\$150', '\$200', '\$300'],
        correctAnswerIndex: 2,
        category: QuizCategory.casinoMath,
        explanation: 'Even money (1:1) means winning \$100 plus original \$100 bet returned = \$200 total.',
        points: 10,
      ),
      Question(
        id: 'cm_b1_3',
        question: 'What does "3:2 payout" mean in Blackjack?',
        options: ['3 cards to 2', 'Win \$3 for every \$2 bet', '3 divided by 2', '5 total'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: '3:2 payout means for every \$2 bet, you win \$3. A \$10 bet wins \$15.',
        points: 10,
      ),
      Question(
        id: 'cm_b1_4',
        question: 'How much does a \$50 bet pay at 3:2 odds?',
        options: ['\$50', '\$75', '\$100', '\$150'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: '\$50 at 3:2 = (\$50 × 3) ÷ 2 = \$75 payout.',
        points: 10,
      ),
      Question(
        id: 'cm_b1_5',
        question: 'What is "probability" in casino gaming?',
        options: ['Luck', 'Mathematical likelihood of an outcome occurring', 'Player skill', 'Dealer choice'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: 'Probability is the mathematical likelihood that a specific outcome will occur.',
        points: 10,
      ),
      Question(
        id: 'cm_b1_6',
        question: 'If you bet \$25 and odds are 2:1, how much profit do you make if you win?',
        options: ['\$25', '\$50', '\$75', '\$100'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: '2:1 odds mean you win \$2 for every \$1 bet. \$25 × 2 = \$50 profit.',
        points: 10,
      ),
      Question(
        id: 'cm_b1_7',
        question: 'What percentage is the house edge if casino expects to keep \$5 from every \$100 wagered?',
        options: ['2%', '5%', '10%', '50%'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: '\$5 out of \$100 = 5% house edge.',
        points: 10,
      ),
      Question(
        id: 'cm_b1_8',
        question: 'What is "RTP" (Return to Player)?',
        options: ['Return the paycheck', 'Percentage of wagered money returned to players over time', 'Poker term', 'Tip amount'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: 'RTP is the percentage of all wagered money that will be paid back to players over time.',
        points: 10,
      ),
    ],
  ),

  // Intermediate
  Quiz(
    id: 'casino_math_intermediate_1',
    title: 'Odds and Payouts',
    category: QuizCategory.casinoMath,
    difficulty: DifficultyLevel.intermediate,
    timeLimit: 540,
    passingScore: 75,
    requiredScore: 400,
    questions: [
      Question(
        id: 'cm_i1_1',
        question: 'In Roulette, what are the true odds of hitting a single number on a 38-number wheel?',
        options: ['35:1', '37:1', '38:1', '36:1'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: 'With 38 numbers, the true odds are 37:1 (37 ways to lose, 1 way to win).',
        points: 10,
      ),
      Question(
        id: 'cm_i1_2',
        question: 'If Roulette pays 35:1 but true odds are 37:1, what is the house edge?',
        options: ['2.7%', '5.26%', '1.35%', '10%'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: 'The difference between payout and true odds creates a 5.26% house edge on double-zero Roulette.',
        points: 10,
      ),
      Question(
        id: 'cm_i1_3',
        question: 'What is the probability of being dealt a blackjack (Ace + 10-value card)?',
        options: ['2.5%', '4.8%', '10%', '50%'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: 'The probability of being dealt a natural blackjack is approximately 4.8%.',
        points: 10,
      ),
      Question(
        id: 'cm_i1_4',
        question: 'If a game has 97% RTP, what is the house edge?',
        options: ['97%', '3%', '7%', '10%'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: 'House edge = 100% - RTP. So 100% - 97% = 3% house edge.',
        points: 10,
      ),
      Question(
        id: 'cm_i1_5',
        question: 'How much is the 5% commission on a \$500 winning Banker bet in Baccarat?',
        options: ['\$5', '\$25', '\$50', '\$100'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: '5% of \$500 = \$500 × 0.05 = \$25 commission.',
        points: 10,
      ),
      Question(
        id: 'cm_i1_6',
        question: 'What is "expected value" in gambling mathematics?',
        options: ['Hope to win', 'Average amount expected to win or lose per bet', 'Maximum win', 'Minimum bet'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: 'Expected value is the average amount a player expects to win or lose per bet over time.',
        points: 10,
      ),
      Question(
        id: 'cm_i1_7',
        question: 'If you make one hundred \$10 bets at a game with 2% house edge, what is expected loss?',
        options: ['\$2', '\$20', '\$200', '\$1000'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: '100 bets × \$10 = \$1000 wagered. \$1000 × 2% = \$20 expected loss.',
        points: 10,
      ),
      Question(
        id: 'cm_i1_8',
        question: 'What is "variance" in casino games?',
        options: ['Dealer change', 'Statistical measure of how results deviate from expected value', 'Rule variation', 'Bet size'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: 'Variance measures how much actual results deviate from the expected value.',
        points: 10,
      ),
    ],
  ),

  // Advanced
  Quiz(
    id: 'casino_math_advanced_1',
    title: 'Advanced Gaming Mathematics',
    category: QuizCategory.casinoMath,
    difficulty: DifficultyLevel.advanced,
    timeLimit: 600,
    passingScore: 80,
    requiredScore: 750,
    questions: [
      Question(
        id: 'cm_a1_1',
        question: 'In Blackjack, what is the approximate probability of dealer busting with a 6 showing?',
        options: ['25%', '35%', '42%', '50%'],
        correctAnswerIndex: 2,
        category: QuizCategory.casinoMath,
        explanation: 'Dealer showing a 6 has approximately 42% probability of busting.',
        points: 10,
      ),
      Question(
        id: 'cm_a1_2',
        question: 'What is "standard deviation" and why is it important for dealers?',
        options: ['Rule change', 'Measure of result spread helping predict bankroll swings', 'Bet limit', 'Shuffle method'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: 'Standard deviation measures result spread and helps predict bankroll fluctuations over time.',
        points: 10,
      ),
      Question(
        id: 'cm_a1_3',
        question: 'How does "penetration" in card games affect house edge?',
        options: ['No effect', 'Deeper penetration slightly increases counter advantage', 'Makes house edge higher', 'Irrelevant'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: 'Deeper deck penetration before shuffling gives card counters more advantageous betting opportunities.',
        points: 10,
      ),
      Question(
        id: 'cm_a1_4',
        question: 'What is the mathematical reasoning behind "never take insurance" advice in Blackjack?',
        options: ['Bad luck', 'Negative expected value - pays 2:1 but true odds are worse than 2.25:1', 'Always take it', 'Superstition'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: 'Insurance has negative expected value because it pays 2:1 but true odds are approximately 2.25:1.',
        points: 10,
      ),
      Question(
        id: 'cm_a1_5',
        question: 'How do casinos calculate "theo" (theoretical win) for players?',
        options: ['Guess', 'Average bet × hands played × house edge', 'Total bets', 'Actual losses'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: 'Theoretical win is calculated as: Average bet size × number of hands × house edge percentage.',
        points: 10,
      ),
      Question(
        id: 'cm_a1_6',
        question: 'What is "Kelly Criterion" in gambling mathematics?',
        options: ['Person\'s name', 'Formula for optimal bet sizing based on edge and bankroll', 'Game rule', 'Payout ratio'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: 'Kelly Criterion is a mathematical formula for determining optimal bet size based on advantage and bankroll.',
        points: 10,
      ),
      Question(
        id: 'cm_a1_7',
        question: 'Why do casinos offer "6:5" Blackjack instead of "3:2"?',
        options: ['Better for players', 'Increases house edge from ~0.5% to ~1.4%', 'Easier math', 'Traditional'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: '6:5 Blackjack payouts increase the house edge significantly compared to traditional 3:2 payouts.',
        points: 10,
      ),
      Question(
        id: 'cm_a1_8',
        question: 'What is "gambler\'s fallacy" and why should dealers understand it?',
        options: ['Betting system', 'False belief that past independent events affect future outcomes', 'Winning strategy', 'Math error'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: 'Gambler\'s fallacy is the false belief that past independent events influence future probabilities.',
        points: 10,
      ),
    ],
  ),

  // Expert
  Quiz(
    id: 'casino_math_expert_1',
    title: 'Expert Gaming Theory',
    category: QuizCategory.casinoMath,
    difficulty: DifficultyLevel.expert,
    timeLimit: 600,
    passingScore: 85,
    requiredScore: 1100,
    questions: [
      Question(
        id: 'cm_e1_1',
        question: 'What is the "true count" in card counting and how is it calculated?',
        options: ['Total cards', 'Running count divided by estimated remaining decks', 'Dealer count', 'Bet total'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: 'True count normalizes the running count by dividing it by the estimated number of remaining decks.',
        points: 10,
      ),
      Question(
        id: 'cm_e1_2',
        question: 'How does "composition-dependent strategy" differ from basic Blackjack strategy?',
        options: ['No difference', 'Accounts for specific card composition, not just totals', 'Simpler', 'Illegal'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: 'Composition-dependent strategy considers specific cards in hand, not just total value.',
        points: 10,
      ),
      Question(
        id: 'cm_e1_3',
        question: 'What is "risk of ruin" in gambling mathematics?',
        options: ['Building damage', 'Probability of losing entire bankroll given specific parameters', 'Cheating', 'Bad luck'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: 'Risk of ruin is the probability of losing your entire bankroll given bet size, edge, and variance.',
        points: 10,
      ),
      Question(
        id: 'cm_e1_4',
        question: 'How does "shuffle tracking" work mathematically?',
        options: ['Random', 'Tracking clumps of favorable cards through shuffle', 'Counting shuffles', 'Impossible'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: 'Shuffle tracking involves following clusters of favorable cards through imperfect shuffle sequences.',
        points: 10,
      ),
      Question(
        id: 'cm_e1_5',
        question: 'What is "N0" (N-zero) in advantage play?',
        options: ['Zero bets', 'Number of hands needed to overcome variance and show actual edge', 'No advantage', 'Neutral count'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: 'N0 represents the number of hands needed for actual results to reflect true mathematical edge.',
        points: 10,
      ),
      Question(
        id: 'cm_e1_6',
        question: 'How do casinos use "standard error" in game protection?',
        options: ['Ignore it', 'Identify statistically improbable dealer or player results', 'Rules', 'Chip colors'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: 'Standard error helps identify results that deviate significantly from expected outcomes, indicating possible cheating.',
        points: 10,
      ),
      Question(
        id: 'cm_e1_7',
        question: 'What is "phantom dealer" statistical analysis?',
        options: ['Ghost stories', 'Analyzing dealer results as if dealer played both hands to detect bias', 'No dealer', 'Shift change'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: 'Phantom dealer analysis evaluates outcomes as if the dealer played both positions to detect bias or advantage play.',
        points: 10,
      ),
      Question(
        id: 'cm_e1_8',
        question: 'How does "edge sorting" exploit mathematical probability?',
        options: ['Card counting', 'Using card back pattern irregularities to identify high-value cards', 'Shuffle method', 'Chip stacking'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoMath,
        explanation: 'Edge sorting exploits manufacturing imperfections on card backs to identify and track high-value cards.',
        points: 10,
      ),
    ],
  ),
];
