import '../models/quiz.dart';

// NEW CATEGORY: Security Procedures - Part 7
final List<Quiz> securityProceduresQuizzes = [
  // Beginner
  Quiz(
    id: 'security_beginner_1',
    title: 'Basic Security Awareness',
    category: QuizCategory.securityProcedures,
    difficulty: DifficultyLevel.beginner,
    timeLimit: 480,
    passingScore: 70,
    questions: [
      Question(
        id: 'sec_b1_1',
        question: 'What should dealers do if they notice suspicious behavior at their table?',
        options: ['Ignore it', 'Notify supervisor immediately while maintaining composure', 'Confront player', 'Leave table'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Suspicious behavior should be reported immediately to supervisors while maintaining professional composure.',
        points: 10,
      ),
      Question(
        id: 'sec_b1_2',
        question: 'What is the primary purpose of casino surveillance cameras?',
        options: ['Decoration', 'Monitor all activities for security and game protection', 'Count players', 'Lighting'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Surveillance cameras monitor all casino activities for security, game protection, and dispute resolution.',
        points: 10,
      ),
      Question(
        id: 'sec_b1_3',
        question: 'What should dealers do if they find an unattended wallet or purse at their table?',
        options: ['Keep it', 'Immediately notify security and document the item', 'Wait', 'Give to players'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Lost items must be immediately reported to security and properly documented.',
        points: 10,
      ),
      Question(
        id: 'sec_b1_4',
        question: 'Why must dealers never leave their table unattended?',
        options: ['Company policy', 'Prevents theft, cheating, and ensures game security', 'Lazy', 'Not important'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Unattended tables are vulnerable to theft, cheating, and security breaches.',
        points: 10,
      ),
      Question(
        id: 'sec_b1_5',
        question: 'What should dealers do if approached by someone claiming to be casino management they don\'t recognize?',
        options: ['Obey immediately', 'Verify identity with supervisor before following instructions', 'Refuse', 'Ignore'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Always verify identity of unfamiliar people claiming authority before following instructions.',
        points: 10,
      ),
      Question(
        id: 'sec_b1_6',
        question: 'What is the purpose of "game protection" training?',
        options: ['Protect games from damage', 'Train dealers to recognize and prevent cheating and security threats', 'Rules only', 'Customer service'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Game protection training teaches dealers to recognize and prevent cheating and security threats.',
        points: 10,
      ),
      Question(
        id: 'sec_b1_7',
        question: 'Why do casinos require dealers to "clear hands" by showing palms?',
        options: ['Greeting', 'Prove not palming chips or cards', 'Exercise', 'Tradition'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Clearing hands shows cameras and supervisors that dealers are not palming chips or cards.',
        points: 10,
      ),
      Question(
        id: 'sec_b1_8',
        question: 'What should dealers do if they witness another dealer breaking security protocols?',
        options: ['Ignore', 'Report to supervisor privately and immediately', 'Gossip', 'Join them'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Protocol violations must be reported privately to supervisors to maintain security integrity.',
        points: 10,
      ),
    ],
  ),

  // Intermediate
  Quiz(
    id: 'security_intermediate_1',
    title: 'Cheating Detection Basics',
    category: QuizCategory.securityProcedures,
    difficulty: DifficultyLevel.intermediate,
    timeLimit: 540,
    passingScore: 75,
    requiredScore: 400,
    questions: [
      Question(
        id: 'sec_i1_1',
        question: 'What is "past posting" in casino cheating?',
        options: ['Mail fraud', 'Adding or changing bets after outcome is known', 'Historical records', 'Job posting'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Past posting is illegally adding or changing bets after the outcome is determined.',
        points: 10,
      ),
      Question(
        id: 'sec_i1_2',
        question: 'How can dealers detect "card marking" schemes?',
        options: ['Impossible', 'Look for ink marks, bends, scratches, or patterns on card backs', 'Trust players', 'Ignore'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Card marking involves ink, bends, scratches, or patterns on card backs that dealers must watch for.',
        points: 10,
      ),
      Question(
        id: 'sec_i1_3',
        question: 'What is "collusion" in casino security terms?',
        options: ['Game type', 'Two or more people working together to cheat', 'Collision', 'Table setup'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Collusion involves two or more people working together to cheat the casino.',
        points: 10,
      ),
      Question(
        id: 'sec_i1_4',
        question: 'What are common signs of "card switching" by players?',
        options: ['None', 'Hand movements near lap or pockets, distraction tactics, unusual card handling', 'Loud talking', 'Winning'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Card switching signs include hand movements to lap/pockets, distractions, and unusual card handling.',
        points: 10,
      ),
      Question(
        id: 'sec_i1_5',
        question: 'What is "chip sliding" or "chip pinching"?',
        options: ['Chip cleaning', 'Illegally adding/removing chips from bets after outcome', 'Chip stacking', 'Chip exchange'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Chip sliding/pinching involves illegally adding or removing chips from bets after the outcome.',
        points: 10,
      ),
      Question(
        id: 'sec_i1_6',
        question: 'How should dealers handle a suspected "cooler deck" (pre-stacked cards) attempt?',
        options: ['Use it', 'Immediately secure deck, notify supervisor, never allow outside decks', 'Ignore', 'Mix it in'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Suspected cooler decks must be secured immediately, supervisor notified, and only house decks used.',
        points: 10,
      ),
      Question(
        id: 'sec_i1_7',
        question: 'What is "card counting" and is it illegal?',
        options: ['Illegal cheating', 'Legal mental tracking of cards; not illegal but casinos can refuse service', 'Counting bets', 'Dealer skill'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Card counting is legal mental tracking, but casinos can refuse service to card counters.',
        points: 10,
      ),
      Question(
        id: 'sec_i1_8',
        question: 'What are "tells" in dealer security awareness?',
        options: ['Stories', 'Unconscious signals or patterns that reveal information', 'Instructions', 'Announcements'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Tells are unconscious signals or patterns that can inadvertently reveal card or game information.',
        points: 10,
      ),
    ],
  ),

  // Advanced
  Quiz(
    id: 'security_advanced_1',
    title: 'Advanced Threat Recognition',
    category: QuizCategory.securityProcedures,
    difficulty: DifficultyLevel.advanced,
    timeLimit: 600,
    passingScore: 80,
    requiredScore: 750,
    questions: [
      Question(
        id: 'sec_a1_1',
        question: 'What is "team play" in advantage gambling and how is it detected?',
        options: ['Group of friends', 'Coordinated players with spotters and big players; detected by betting patterns', 'Tournament', 'Regular play'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Team play involves coordinated advantage players with spotters and big players, detected by betting patterns.',
        points: 10,
      ),
      Question(
        id: 'sec_a1_2',
        question: 'What is "hole carding" and how do dealers prevent it?',
        options: ['Card damage', 'Seeing dealer hole card; prevented by proper card protection techniques', 'Chip technique', 'Counting'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Hole carding is seeing the dealer\'s hole card; prevented by proper card protection and handling.',
        points: 10,
      ),
      Question(
        id: 'sec_a1_3',
        question: 'What is a "surveillance eye" and how should dealers interact with it?',
        options: ['Camera', 'Live surveillance operator monitoring tables; dealers work professionally knowing they\'re watched', 'Supervisor', 'Decoration'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Surveillance eyes are live operators monitoring tables; dealers should work professionally knowing they\'re observed.',
        points: 10,
      ),
      Question(
        id: 'sec_a1_4',
        question: 'How do casinos use "facial recognition" technology in security?',
        options: ['Not used', 'Identify known cheaters, advantage players, and banned individuals', 'Employee time', 'Marketing only'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Facial recognition identifies known cheaters, advantage players, and individuals banned from the property.',
        points: 10,
      ),
      Question(
        id: 'sec_a1_5',
        question: 'What is "false shuffling" and how is it a security concern?',
        options: ['Shuffle mistake', 'Deliberately maintaining card order while appearing to shuffle; major cheating method', 'Slow shuffle', 'Extra shuffle'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'False shuffling maintains card order while appearing to shuffle, enabling major cheating schemes.',
        points: 10,
      ),
      Question(
        id: 'sec_a1_6',
        question: 'How should dealers respond to "distraction tactics" used by cheaters?',
        options: ['Get distracted', 'Maintain focus on game, follow procedures, report unusual distractions', 'Engage', 'Leave table'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Dealers must maintain focus despite distractions, follow all procedures, and report unusual tactics.',
        points: 10,
      ),
      Question(
        id: 'sec_a1_7',
        question: 'What is "RFID" technology use in modern casino security?',
        options: ['Radio decoration', 'Radio-frequency chips enabling tracking and authentication', 'WiFi', 'Phone system'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'RFID (Radio-Frequency Identification) embedded in chips enables tracking and authentication.',
        points: 10,
      ),
      Question(
        id: 'sec_a1_8',
        question: 'What is "dealer-player collusion" and what are its indicators?',
        options: ['Friendship', 'Illegal cooperation for cheating; indicated by overpayments, errors favoring one player', 'Good service', 'Normal'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Dealer-player collusion involves illegal cooperation, indicated by systematic overpayments or favorable errors.',
        points: 10,
      ),
    ],
  ),

  // Expert
  Quiz(
    id: 'security_expert_1',
    title: 'Expert Security Operations',
    category: QuizCategory.securityProcedures,
    difficulty: DifficultyLevel.expert,
    timeLimit: 600,
    passingScore: 85,
    requiredScore: 1100,
    questions: [
      Question(
        id: 'sec_e1_1',
        question: 'What is "advantage play analytics" in modern casinos?',
        options: ['Game rules', 'Mathematical and behavioral analysis to identify skilled players', 'Accounting', 'Marketing'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Advantage play analytics uses math and behavioral analysis to identify players with an edge over the house.',
        points: 10,
      ),
      Question(
        id: 'sec_e1_2',
        question: 'How does "shuffle mapping" work as an advantage play technique?',
        options: ['Random', 'Tracking card sequences through predictable shuffle patterns', 'Shuffle counting', 'Impossible'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Shuffle mapping tracks card sequences through predictable or imperfect shuffle patterns.',
        points: 10,
      ),
      Question(
        id: 'sec_e1_3',
        question: 'What is "computer-aided play" and why is it illegal in casinos?',
        options: ['Allowed', 'Using electronic devices to calculate odds/strategy; illegal in all US jurisdictions', 'Phone apps', 'Calculators ok'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Computer-aided play uses electronic devices for odds calculation and is illegal in all US gaming jurisdictions.',
        points: 10,
      ),
      Question(
        id: 'sec_e1_4',
        question: 'What is "the Griffin Book" in casino security?',
        options: ['Novel', 'Historical database of known cheaters shared among casinos', 'Rulebook', 'Training manual'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'The Griffin Book was a shared database of known cheaters and advantage players used by casinos.',
        points: 10,
      ),
      Question(
        id: 'sec_e1_5',
        question: 'How do casinos use "bet correlation analysis" in security?',
        options: ['Not used', 'Statistical analysis linking betting patterns to count or advantage play', 'Accounting', 'Random checks'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Bet correlation analysis uses statistics to link betting patterns with card counting or advantage play.',
        points: 10,
      ),
      Question(
        id: 'sec_e1_6',
        question: 'What is "phantom dealer analysis" in security investigations?',
        options: ['Ghost stories', 'Analyzing outcomes as if dealer played both positions to detect cheating', 'No dealer', 'Extra dealer'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Phantom dealer analysis evaluates outcomes as if dealer held both positions to statistically detect cheating.',
        points: 10,
      ),
      Question(
        id: 'sec_e1_7',
        question: 'What are "biometric security systems" used for in casinos?',
        options: ['Decoration', 'Fingerprint, iris, facial recognition for access control and fraud prevention', 'Lighting', 'Marketing'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Biometric systems use fingerprints, iris scans, and facial recognition for security and fraud prevention.',
        points: 10,
      ),
      Question(
        id: 'sec_e1_8',
        question: 'What is "preferential shuffling" detection and why is it important?',
        options: ['Shuffle preference', 'Identifying dealers who shuffle when count favors players; indicates awareness', 'Random', 'Style'],
        correctAnswerIndex: 1,
        category: QuizCategory.securityProcedures,
        explanation: 'Preferential shuffling detection identifies when dealers shuffle favorable counts, indicating possible collusion.',
        points: 10,
      ),
    ],
  ),
];
