// Part 4: Casino Protocol & General Knowledge Quizzes
import '../models/quiz.dart';

final casinoProtocolQuizzes = [
  // BEGINNER
  Quiz(
    id: 'casino_protocol_beginner_1',
    title: 'Casino Procedures 101',
    category: QuizCategory.casinoProtocol,
    difficulty: DifficultyLevel.beginner,
    timeLimit: 480,
    passingScore: 70,
    questions: [
      Question(
        id: 'cp_b1_1',
        question: 'Why must dealers "clear their hands" by clapping and showing palms?',
        options: ['Tradition', 'Show surveillance they have nothing in hands', 'Stretch hands', 'Signal others'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoProtocol,
        explanation: 'Dealers clear hands to show surveillance cameras they aren\'t palming chips or cards, ensuring transparency.',
        points: 10,
      ),
      Question(
        id: 'cp_b1_2',
        question: 'What does "table is open/closed" mean?',
        options: ['Needs cleaning', 'Whether accepting new players or being closed', 'Drink service status', 'Break time'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoProtocol,
        explanation: 'This indicates whether the table is actively accepting players or is being closed/prepared.',
        points: 10,
      ),
      Question(
        id: 'cp_b1_3',
        question: 'What should dealers never do with their hands during dealing?',
        options: ['Touch face or pockets', 'Deal cards', 'Stack chips', 'Shuffle cards'],
        correctAnswerIndex: 0,
        category: QuizCategory.casinoProtocol,
        explanation: 'Dealers should never touch their face, hair, or pockets to maintain game integrity and prevent accusations.',
        points: 10,
      ),
      Question(
        id: 'cp_b1_4',
        question: 'What is a "fill" in casino operations?',
        options: ['Adding players', 'Bringing more chips to table', 'Refilling drinks', 'Replacing cards'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoProtocol,
        explanation: 'A fill is when additional chips are brought to a table to replenish the dealer\'s chip tray.',
        points: 10,
      ),
      Question(
        id: 'cp_b1_5',
        question: 'What is a "credit" in casino operations?',
        options: ['Player points', 'Removing excess chips from table', 'Dealer score', 'Customer discount'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoProtocol,
        explanation: 'A credit is when excess chips are removed from the dealer\'s tray and returned to the cage.',
        points: 10,
      ),
      Question(
        id: 'cp_b1_6',
        question: 'What is the "eye in the sky"?',
        options: ['Ceiling lights', 'Surveillance camera system', 'Smoke detectors', 'Air vents'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoProtocol,
        explanation: '"Eye in the sky" refers to the surveillance camera system monitoring all gaming activities.',
        points: 10,
      ),
      Question(
        id: 'cp_b1_7',
        question: 'Why must all dealer actions be visible to cameras?',
        options: ['Better lighting', 'Security and dispute resolution', 'Training purposes', 'Player entertainment'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoProtocol,
        explanation: 'All actions must be visible to cameras for security monitoring and resolving any disputes that arise.',
        points: 10,
      ),
      Question(
        id: 'cp_b1_8',
        question: 'What should dealers do when their shift ends?',
        options: ['Leave immediately', 'Wait for relief, count out tray, get supervisor sign-off', 'Just walk away', 'Lock the table'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoProtocol,
        explanation: 'Dealers must wait for relief, count out their chip tray with supervisor verification before leaving.',
        points: 10,
      ),
    ],
  ),

  // INTERMEDIATE
  Quiz(
    id: 'casino_protocol_intermediate_1',
    title: 'Advanced Casino Procedures',
    category: QuizCategory.casinoProtocol,
    difficulty: DifficultyLevel.intermediate,
    timeLimit: 540,
    passingScore: 75,
    requiredScore: 550,
    questions: [
      Question(
        id: 'cp_i1_1',
        question: 'What is "cage" in casino terminology?',
        options: ['Security area', 'Cashier where chips are exchanged for money', 'Card storage', 'Break room'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoProtocol,
        explanation: 'The cage is the casino cashier area where chips are exchanged for cash and financial transactions occur.',
        points: 10,
      ),
      Question(
        id: 'cp_i1_2',
        question: 'What is a "marker" in casino terms?',
        options: ['Table sign', 'Casino credit/IOU for high-rollers', 'Chip color', 'Card indicator'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoProtocol,
        explanation: 'A marker is essentially an IOU or line of credit extended to qualified players by the casino.',
        points: 10,
      ),
      Question(
        id: 'cp_i1_3',
        question: 'What does "86" mean in casino speak?',
        options: ['Lucky number', 'Person banned from casino', 'Table number', 'Shift code'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoProtocol,
        explanation: '"86" means a person has been banned or removed from the casino premises.',
        points: 10,
      ),
      Question(
        id: 'cp_i1_4',
        question: 'What is a "comp" in casino operations?',
        options: ['Computer', 'Complimentary service given to players', 'Competition', 'Complaint'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoProtocol,
        explanation: 'A comp is a complimentary service (meals, rooms, shows) given to players based on their play.',
        points: 10,
      ),
      Question(
        id: 'cp_i1_5',
        question: 'What is the proper procedure for a table game opening?',
        options: ['Just start dealing', 'Count and verify everything with supervisor and surveillance', 'Flip table sign', 'Announce loudly'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoProtocol,
        explanation: 'Table openings require counting/verifying all chips, cards, and equipment with supervisor under camera.',
        points: 10,
      ),
      Question(
        id: 'cp_i1_6',
        question: 'What should dealers do if they suspect cheating?',
        options: ['Confront player', 'Discreetly signal supervisor without alerting suspects', 'Announce it', 'Ignore it'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoProtocol,
        explanation: 'Suspected cheating should be discreetly signaled to supervisors/security without alerting the suspects.',
        points: 10,
      ),
      Question(
        id: 'cp_i1_7',
        question: 'What is "past posting"?',
        options: ['Advertising', 'Illegally placing bets after outcome is known', 'Posting scores', 'Social media'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoProtocol,
        explanation: 'Past posting is a cheating technique where bets are placed or changed after the outcome is already determined.',
        points: 10,
      ),
      Question(
        id: 'cp_i1_8',
        question: 'What is proper protocol for handling a "disputed payout"?',
        options: ['Argue with player', 'Stop game, call supervisor, preserve bet layout, review cameras', 'Pay again', 'Ask other players'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoProtocol,
        explanation: 'Disputed payouts require stopping play, calling supervisor, preserving evidence, and reviewing surveillance.',
        points: 10,
      ),
    ],
  ),

  // ADVANCED
  Quiz(
    id: 'casino_protocol_advanced_1',
    title: 'Expert Casino Operations',
    category: QuizCategory.casinoProtocol,
    difficulty: DifficultyLevel.advanced,
    timeLimit: 600,
    passingScore: 80,
    requiredScore: 800,
    questions: [
      Question(
        id: 'cp_a1_1',
        question: 'What is a "soft count" room?',
        options: ['Quiet room', 'Where paper money is counted', 'Training area', 'Break room'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoProtocol,
        explanation: 'The soft count room is a highly secure area where all paper currency from table drop boxes is counted.',
        points: 10,
      ),
      Question(
        id: 'cp_a1_2',
        question: 'What is the purpose of "table inventory"?',
        options: ['Count players', 'Verify exact chip value in dealer tray at shift changes', 'Count cards', 'List equipment'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoProtocol,
        explanation: 'Table inventory ensures accountability by verifying exact chip values during shift changes and table closures.',
        points: 10,
      ),
      Question(
        id: 'cp_a1_3',
        question: 'What is "advantage play" and how is it different from cheating?',
        options: ['Same as cheating', 'Legal strategic play using game information', 'Dealer error', 'Casino promotion'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoProtocol,
        explanation: 'Advantage play uses legal strategies (like card counting) to gain edge, unlike cheating which breaks rules.',
        points: 10,
      ),
      Question(
        id: 'cp_a1_4',
        question: 'What is a "CSM" in modern casinos?',
        options: ['Casino Security Manager', 'Continuous Shuffle Machine', 'Customer Service Manual', 'Chip Storage Module'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoProtocol,
        explanation: 'A CSM (Continuous Shuffle Machine) automatically shuffles cards continuously, eliminating card counting.',
        points: 10,
      ),
      Question(
        id: 'cp_a1_5',
        question: 'What is "hole carding" and why must dealers prevent it?',
        options: ['Card damage', 'Seeing dealer\'s hole card prematurely', 'Shuffling technique', 'Chip technique'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoProtocol,
        explanation: 'Hole carding is when players glimpse the dealer\'s hole card, giving unfair advantage. Proper technique prevents this.',
        points: 10,
      ),
      Question(
        id: 'cp_a1_6',
        question: 'What are "gaming regulations" and who enforces them?',
        options: ['Casino rules', 'State/jurisdiction laws enforced by gaming commission', 'Player guidelines', 'Dealer handbook'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoProtocol,
        explanation: 'Gaming regulations are state/jurisdiction laws enforced by gaming commissions that govern all casino operations.',
        points: 10,
      ),
      Question(
        id: 'cp_a1_7',
        question: 'What is the purpose of "minimum internal control standards" (MICS)?',
        options: ['Player limits', 'Required security and accounting procedures for casinos', 'Temperature control', 'Dress codes'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoProtocol,
        explanation: 'MICS are regulatory requirements establishing minimum security, accounting, and operational procedures.',
        points: 10,
      ),
      Question(
        id: 'cp_a1_8',
        question: 'What is "title 31" compliance in casinos?',
        options: ['Age requirement', 'Anti-money laundering reporting requirements', 'Liquor license', 'Building code'],
        correctAnswerIndex: 1,
        category: QuizCategory.casinoProtocol,
        explanation: 'Title 31 requires casinos to report large cash transactions to prevent money laundering and illegal activities.',
        points: 10,
      ),
    ],
  ),
];

final generalKnowledgeQuizzes = [
  // BEGINNER
  Quiz(
    id: 'general_beginner_1',
    title: 'Casino Dealer Career Basics',
    category: QuizCategory.general,
    difficulty: DifficultyLevel.beginner,
    timeLimit: 480,
    passingScore: 70,
    questions: [
      Question(
        id: 'gk_b1_1',
        question: 'What is the minimum age to work as casino dealer in most jurisdictions?',
        options: ['18', '19', '21', '25'],
        correctAnswerIndex: 2,
        category: QuizCategory.general,
        explanation: 'Most jurisdictions require dealers to be 21, the same age as the legal gambling age.',
        points: 10,
      ),
      Question(
        id: 'gk_b1_2',
        question: 'What is the typical dealer rotation time?',
        options: ['10 minutes', '20-30 minutes', '1 hour', '4 hours'],
        correctAnswerIndex: 1,
        category: QuizCategory.general,
        explanation: 'Dealers typically rotate every 20-30 minutes to maintain focus and prevent fatigue.',
        points: 10,
      ),
      Question(
        id: 'gk_b1_3',
        question: 'What qualities are most important for a successful dealer?',
        options: ['Math skills only', 'Manual dexterity, math, customer service, attention to detail', 'Being entertaining', 'Gambling knowledge'],
        correctAnswerIndex: 1,
        category: QuizCategory.general,
        explanation: 'Successful dealers need technical skills, math ability, customer service, and unwavering attention to detail.',
        points: 10,
      ),
      Question(
        id: 'gk_b1_4',
        question: 'How long is typical dealer training?',
        options: ['1 day', '2-8 weeks depending on game', '6 months', '1 year'],
        correctAnswerIndex: 1,
        category: QuizCategory.general,
        explanation: 'Dealer training typically ranges from 2-8 weeks depending on the complexity of the game being learned.',
        points: 10,
      ),
      Question(
        id: 'gk_b1_5',
        question: 'What is a dealer school?',
        options: ['Elementary school', 'Specialized training facility for casino dealers', 'Online course', 'Casino building'],
        correctAnswerIndex: 1,
        category: QuizCategory.general,
        explanation: 'Dealer schools are specialized training facilities where aspiring dealers learn game procedures and techniques.',
        points: 10,
      ),
      Question(
        id: 'gk_b1_6',
        question: 'Do dealers typically work full-time or part-time?',
        options: ['Only full-time', 'Only part-time', 'Both options are common', 'Contract only'],
        correctAnswerIndex: 2,
        category: QuizCategory.general,
        explanation: 'Casinos employ both full-time and part-time dealers to cover 24/7 operations and varying business levels.',
        points: 10,
      ),
      Question(
        id: 'gk_b1_7',
        question: 'What shift work is common for dealers?',
        options: ['9-5 only', 'Day, swing, and graveyard shifts 24/7', 'Weekdays only', 'Flexible remote'],
        correctAnswerIndex: 1,
        category: QuizCategory.general,
        explanation: 'Dealers work rotating shifts including days, evenings (swing), and overnight (graveyard) as casinos operate 24/7.',
        points: 10,
      ),
      Question(
        id: 'gk_b1_8',
        question: 'Is dealer income primarily salary or tips?',
        options: ['Only salary', 'Mostly tips (tokes) plus base wage', 'Commission based', 'Profit sharing'],
        correctAnswerIndex: 1,
        category: QuizCategory.general,
        explanation: 'Most dealer income comes from pooled tips (tokes), with a base hourly wage that may be minimum wage.',
        points: 10,
      ),
    ],
  ),

  // INTERMEDIATE
  Quiz(
    id: 'general_intermediate_1',
    title: 'Dealer Career Development',
    category: QuizCategory.general,
    difficulty: DifficultyLevel.intermediate,
    timeLimit: 540,
    passingScore: 75,
    requiredScore: 600,
    questions: [
      Question(
        id: 'gk_i1_1',
        question: 'What is a "dual-rate" dealer?',
        options: ['Works two casinos', 'Works as dealer and supervisor in different shifts', 'Double pay', 'Trainee'],
        correctAnswerIndex: 1,
        category: QuizCategory.general,
        explanation: 'A dual-rate dealer alternates between dealing and supervisory duties, typically earning two different pay rates.',
        points: 10,
      ),
      Question(
        id: 'gk_i1_2',
        question: 'What career advancement is available for dealers?',
        options: ['None', 'Floor supervisor, pit boss, casino management', 'Only lateral moves', 'Casino owner'],
        correctAnswerIndex: 1,
        category: QuizCategory.general,
        explanation: 'Dealers can advance to floor supervisor, pit boss, shift manager, and eventually casino management positions.',
        points: 10,
      ),
      Question(
        id: 'gk_i1_3',
        question: 'What is a "break-in" dealer?',
        options: ['Security', 'New dealer in training or probationary period', 'Substitute', 'Part-timer'],
        correctAnswerIndex: 1,
        category: QuizCategory.general,
        explanation: 'A break-in dealer is someone newly hired who is still in training or probationary status.',
        points: 10,
      ),
      Question(
        id: 'gk_i1_4',
        question: 'How many games should a dealer know to be most employable?',
        options: ['1 is enough', '3-5 different games', '10+ games', 'Just blackjack'],
        correctAnswerIndex: 1,
        category: QuizCategory.general,
        explanation: 'Dealers who can deal 3-5 different games (blackjack, roulette, craps, poker, baccarat) are most employable.',
        points: 10,
      ),
      Question(
        id: 'gk_i1_5',
        question: 'What is the difference between carnival games and traditional table games?',
        options: ['Location', 'Carnival games are newer specialty games vs. classic games', 'Time of day', 'Player type'],
        correctAnswerIndex: 1,
        category: QuizCategory.general,
        explanation: 'Carnival games (like Three Card Poker, Let It Ride) are newer specialty games vs. traditional classics.',
        points: 10,
      ),
      Question(
        id: 'gk_i1_6',
        question: 'What physical demands does dealing require?',
        options: ['Minimal', 'Standing for long periods, repetitive hand motions, concentration', 'Heavy lifting', 'Running'],
        correctAnswerIndex: 1,
        category: QuizCategory.general,
        explanation: 'Dealing requires standing 8+ hours, repetitive hand movements, and intense concentration which can be physically demanding.',
        points: 10,
      ),
      Question(
        id: 'gk_i1_7',
        question: 'Are dealers allowed to gamble at their own casino?',
        options: ['Yes, anytime', 'Usually prohibited by policy and law', 'Only on days off', 'Only certain games'],
        correctAnswerIndex: 1,
        category: QuizCategory.general,
        explanation: 'Most casinos and jurisdictions prohibit dealers from gambling at their employer casino to prevent conflicts.',
        points: 10,
      ),
      Question(
        id: 'gk_i1_8',
        question: 'What is "dealer integrity"?',
        options: ['Physical health', 'Ethical conduct, honesty, and trustworthiness in all dealings', 'Card skills', 'Work schedule'],
        correctAnswerIndex: 1,
        category: QuizCategory.general,
        explanation: 'Dealer integrity encompasses ethical conduct, honesty, trustworthiness, and adherence to all rules and regulations.',
        points: 10,
      ),
    ],
  ),

  // EXPERT
  Quiz(
    id: 'general_expert_1',
    title: 'Master Dealer Knowledge',
    category: QuizCategory.general,
    difficulty: DifficultyLevel.expert,
    timeLimit: 600,
    passingScore: 85,
    requiredScore: 1000,
    questions: [
      Question(
        id: 'gk_e1_1',
        question: 'What is the history of the modern casino dealer profession?',
        options: ['Started in 2000s', 'Evolved from riverboat gambling and Las Vegas boom in 1940s-50s', 'Ancient Rome', 'Medieval Europe'],
        correctAnswerIndex: 1,
        category: QuizCategory.general,
        explanation: 'Modern dealing professionalized during riverboat gambling era and Las Vegas expansion in 1940s-1950s.',
        points: 10,
      ),
      Question(
        id: 'gk_e1_2',
        question: 'How has technology changed dealing in modern casinos?',
        options: ['No changes', 'Automated shufflers, RFID chips, electronic tracking, hybrid tables', 'Eliminated dealers', 'Only cameras'],
        correctAnswerIndex: 1,
        category: QuizCategory.general,
        explanation: 'Technology introduced auto-shufflers, RFID chip tracking, electronic systems, and hybrid live/electronic tables.',
        points: 10,
      ),
      Question(
        id: 'gk_e1_3',
        question: 'What are the key differences between dealing in different countries?',
        options: ['None', 'Regulatory rules, game variations, tipping customs, procedures vary significantly', 'Language only', 'Currency only'],
        correctAnswerIndex: 1,
        category: QuizCategory.general,
        explanation: 'Countries differ in regulations, game rules, tipping practices, dealing procedures, and cultural expectations.',
        points: 10,
      ),
      Question(
        id: 'gk_e1_4',
        question: 'What is the impact of online/live dealer gaming on traditional dealing?',
        options: ['Eliminated jobs', 'Created new opportunities in live streaming studios', 'No impact', 'Replaced all dealers'],
        correctAnswerIndex: 1,
        category: QuizCategory.general,
        explanation: 'Online live dealer gaming created new studio dealing jobs, combining traditional skills with broadcast elements.',
        points: 10,
      ),
      Question(
        id: 'gk_e1_5',
        question: 'What professional organizations exist for casino dealers?',
        options: ['None', 'Various dealer unions and professional associations by region', 'One global union', 'Only management groups'],
        correctAnswerIndex: 1,
        category: QuizCategory.general,
        explanation: 'Multiple dealer unions and professional associations exist regionally to represent dealer interests and rights.',
        points: 10,
      ),
      Question(
        id: 'gk_e1_6',
        question: 'What is the future outlook for the dealer profession?',
        options: ['Obsolete soon', 'Evolving with technology but human dealers remain valued for experience', 'Completely automated', 'Unknown'],
        correctAnswerIndex: 1,
        category: QuizCategory.general,
        explanation: 'While technology advances, human dealers remain valuable for customer experience, though roles are evolving.',
        points: 10,
      ),
      Question(
        id: 'gk_e1_7',
        question: 'What certifications or licenses do dealers need?',
        options: ['None', 'Gaming license from regulatory body in their jurisdiction', 'College degree', 'Medical certificate'],
        correctAnswerIndex: 1,
        category: QuizCategory.general,
        explanation: 'Dealers must obtain a gaming license from their jurisdiction\'s gaming commission after background checks.',
        points: 10,
      ),
      Question(
        id: 'gk_e1_8',
        question: 'What is the most challenging aspect of a dealing career?',
        options: ['Learning rules', 'Managing stress, irregular hours, difficult customers, physical demands', 'Math', 'Uniforms'],
        correctAnswerIndex: 1,
        category: QuizCategory.general,
        explanation: 'The combination of stress management, irregular schedules, challenging customers, and physical demands is most challenging.',
        points: 10,
      ),
    ],
  ),
];
